### ISSUE TITLE
Bug in bios.lua through 'disable Lua 5.1 features'

### ISSUE THREAD

**Issue by magiczocker10** [MCJack123/craftos2#110]
**Describe the bug**
When setting 'disable_lua51_features' to true, the CraftOS-PC won't start anymore, because table.maxn is set to nil.

**To Reproduce**
1. Open the global.json and set the 'disable_lua51_features' to true
2. Start CraftOS-PC

**Expected behavior**
The CraftOS-PC should still start.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59317952/81472692-1184f880-91fa-11ea-9a70-34d26a99529b.png)

**Environment:**
 - OS: Windows
 - Version 2.3.0.0
 - Compiled from source? No

**Comment by MCJack123** [comment]
Fixed in MCJack123/craftos2-rom@17f88a77bfae848ad836356b3d9b17c2d9cbd54f
