### ISSUE TITLE
Long-duraction timers (specifically `os.sleep`, tested at 10s) take way too long to fire

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#115]
**The bug**
I have a line in one of my programs that reads `os.sleep(10)`. In CCEmuX it works fine and resumes after ten seconds. In CraftOS-PC it just.... freezes, though I can terminate it.

**To Reproduce**
1. Type `os.sleep(10)` into the Lua REPL.
2. Does not sleep 10 seconds. Sleeps much longer.

**Expected behavior**
Should sleep 10 seconds.

**Environment**
 - OS: Manjaro Linux, KDE desktop, aarch64 (Pinebook Pro, Rockchip RK3399)
 - Version: CraftOS-PC 2 (git)
 - Compiled from source? Yes, through `yay -S craftos-pc-git`

**Comment by MCJack123** [comment]
1. Can you send the output of the "about" command (or `craftos --version`)? The `craftos-pc-git` package may have had an issue where it wasn't updating past 2.3.0, but this has been fixed.
2. This was a known issue in some older versions, but was supposed to have been fixed recently. Try updating and see if that fixes it.

**Comment by Ocawesome101** [comment]
```
ocawesome101@manjaro-pbp: ~$ craftos --version
CraftOS-PC v2.3.3
Built with: cli mixer print_html
Copyright (c) 2019-2020 JackMacWindows. Licensed under the MIT License.
```
I'll try updating.
