### ISSUE TITLE
craftos-pc-git package build fails

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#117]
**Description**
`yay -S craftos-pc-git` works fine up until it actually tries to `make` craftos-pc - Below is the last few lines of output.
```
[...]
checking hpdf.h usability... no
checking hpdf.h presence... no
checking for hpdf.h... no
checking for library containing HPDF_New... no
configure: creating ./config.status
config.status: creating Makefile
make: *** No targets.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...
Error making: craftos-pc-git
```

**Environment**
 - OS: Manjaro KDE aarch64
 - Version: Latest `craftos-pc-git` from AUR
 - Compiled from source? Yes

**Comment by MCJack123** [comment]
I suspect this was caused by a bad `sed` call that replaced too much of the Makefile. I've updated the package to use `CPPFLAGS` to add the text, instead of adding it in afterwards. Try installing again.

**Comment by Ocawesome101** [comment]
It works. Thank you :)
