### ISSUE TITLE
Table output in lua

### ISSUE THREAD

**Issue by magiczocker10** [MCJack123/craftos2#125]
**Describe the bug**
When using "table_name = {"value1",nil,"value2"}, the output of the table is {"value1", "value2"} while table_name[2] is still nil.

**To Reproduce**
1. open the lua shell
2. create a table with {"value1",nil,"value2"}
3. type in the name of the table to display it
 
**Expected behavior**
To see the expected behavior, create a new blank table with "table_variable = {}" and add the two values seperatly with table_value[1] = "value1" and table_value[3] = "value2". The result can also be seen in the image below.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59317952/88061031-45b85600-cb67-11ea-9de7-5fb835ece4bc.png)

**Environment (please complete the following information):**
 - OS: Windows 10 20H1
 - Version v2.3.4
 - Compiled from source? No

**Additional content**
textutils.serialize outputs the expected results in both cases.

**Comment by MCJack123** [comment]
Fixed in MCJack123/craftos2-rom@22b5fd778d5af2b3d2beab1f9c91e2794517cef8
