### ISSUE TITLE
Adding numbers together is sometimes weird.

### ISSUE THREAD

**Issue by magiczocker10** [MCJack123/craftos2#128]
**Describe the bug**
Adding numbers over and over again makes the result broken.

**To Reproduce**
1. Execute:
local a = 0
for i=1, 500 do
a = a + 0.2
print(a)
end
2. See the results of it.

**Expected behavior**
Always add 0.2 to the variable "a".

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59317952/89123078-f231fa80-d4cc-11ea-8e4d-ecc1fc45b700.png)

**Environment:**
 - OS: Windows 10 20H1
 - Version 2.3.4
 - Compiled from source? No

**Comment by SquidDev** [comment]
I don't think this is especially odd behaviour - floating points are always going to lose precision.

**Comment by MCJack123** [comment]
SquidDev is correct, this is an issue with anything that uses floating-point numbers due to the nature of computers. You can use `print(string.format("%.2f", n)` to print the number with only 2 digits of precision.
