### ISSUE TITLE
Profiler from debugger crashes and reduces the fps in CraftOS-PC 2.4

### ISSUE THREAD

**Issue by magiczocker10** [MCJack123/craftos2#129]
**Describe the bug**
When using the profiler, CraftOS-PC could crash.

**To Reproduce**
1. Start the debugger with periphemu.create(1,"debugger")
2. Go to the profiler-tab
3. Start the profiler
4. Use the main window.

**Expected behavior**
CraftOS-PC shouldn't crash.

**Environment:**
 - OS: Windows 20H1
 - Version 2.4
 - Compiled from source? No

**Comment by magiczocker10** [comment]
When the debugger is open, the performance is lower than without (lower fps).

**Comment by MCJack123** [comment]
The slowdown with a debugger is known [and documented](https://www.craftos-pc.cc/docs/debugger).
> Note that in CraftOS-PC v2.3 and later, the debugger will reduce the speed of the emulator due to some technical limitations of Lua. (In reality, it's actually that not having the debugger increases speed.)

Regarding the crash: please send the crash dump file at `C:\Users\<your user>\AppData\Local\CrashDumps\CraftOS-PC.<number>.exe`. Look for the most recent file with CraftOS-PC in the name and attach that here.

**Comment by magiczocker10** [comment]
Here is my latest crashdump from CraftOS-PC:
[CraftOS-PC.exe.4004.zip](https://github.com/MCJack123/craftos2/files/5080098/CraftOS-PC.exe.4004.zip)

**Comment by MCJack123** [comment]
Thank you. Indeed, the bug fixed in ff22610 is the same bug you reported.
