### ISSUE TITLE
Keyboard layout is ignored

### ISSUE THREAD

**Issue by JakobDev** [MCJack123/craftos2#138]
**Describe the bug**
CraftOS2 ignores the keyboard layout. e.g on German keyboard z and y are swapped. That means, if you press y on a German keyboard CraftOS2 will think you press z.

**To Reproduce**
Change the keyboard layout of your PC.

**Expected behavior**
Keys should work right.

**Screenshots**
None

**Environment (please complete the following information):**
 - OS: Ubuntu Mate 20.04
 - Version 2.4.3
 - Compiled from source? No

**Additional context**
None

**Comment by MCJack123** [comment]
One note on the implementation of this fix: SDL only changes the keyboard layout according to your language settings, so in your case it will only set the layout to QWERTZ if your language is set to German. It may not work if you set your language to English but your keyboard layout to QWERTZ. (This only affects the `key` events. `char` is not affected.)
