### ISSUE TITLE
Crash on Windows on startup

### ISSUE THREAD

**Issue by Lignum** [MCJack123/craftos2#14]
Upon starting the program, I immediately get this error:
![](https://i.imgur.com/tNkiAlm.png)

**Comment by MCJack123** [comment]
1. CraftOS-PC is only built for 64-bit systems. Ensure your version of Windows is 64-bit.
2. CraftOS-PC requires the [Visual C++ 2015 Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe). Try installing that.

**Comment by MCJack123** [comment]
Also, I've updated the installer and verified it works on a fresh VM. If the above solutions didn't help, try downloading the setup again.

**Comment by Lignum** [comment]
Yep, downloading the installer again fixed it. Thanks.
