### ISSUE TITLE
Add iOS platform support

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#147]
**Is your feature request related to a problem? Please describe.**
CraftOS-PC could theoretically support iOS, but no platform support is present currently.

**Describe the solution you'd like**
Add a CraftOS-PC platform file, and possibly an Xcode project file for building.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LoganDark** [comment]
Why iOS before Android?

**Comment by MCJack123** [comment]
> 
> 
> Why iOS before Android?

I don't have any Android devices to test on, and since Android uses Java instead of C++, I'll need to use the NDK to get it running as an app. iOS natively supports C++, and most of the work required for the platform files is already written in the Mac App source. In fact, I already have the file written; I just haven't had a chance to recompile the libraries for iOS yet.

**Comment by LoganDark** [comment]
> I don't have any Android devices to test on

Well, if you ever consider Android support, I can volunteer as a tester. I only have one Android device, but it runs Android 10, and it's rooted so I can give logs and stuff if something breaks

**Comment by MCJack123** [comment]
This was mostly implemented in a53745b2feeed4f4050fed63258c748b3a098cce (along with a basic Android version), but it needs to be tested.
