### ISSUE TITLE
Add optional width and height options to term.drawPixels

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#148]
**Is your feature request related to a problem? Please describe.**
Currently `term.drawPixels` relies on the length operator to get the size of tables, which stops at the first `nil`. This prevents the ability to skip certain pixels.

**Describe the solution you'd like**
Add two optional arguments to `term.drawPixels` that override the width and height of the table. The width will not be effective when using strings for each row. If one isn't specified, it will be replaced with the table's length.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LoganDark** [comment]
You could also allow negative numbers for "transparent"
