### ISSUE TITLE
Pixels are being slow and also coming back after being changed?

### ISSUE THREAD

**Issue by LoganDark** [MCJack123/craftos2#161]
Quick note: I'm incredibly sad that I have to spoil this early because it's so close to completion, but there are more bugs that are getting in my way, and unfortunately this one I can't fix on my own.

**Describe the bug**
There is some weird behavior going on... pixel updates are a lot slower than they used to be and pixels are coming back after being cleared. It started happening out of nowhere (after working fine before), and it persists across restarts.

**To Reproduce**
Absolutely no idea

**Expected behavior**
No reverting

**Screenshots**
https://user-images.githubusercontent.com/4723091/102898303-2a0af180-441e-11eb-9081-c87d40eefb32.mp4

Yeah... that's the shell and `edit` running in graphics mode. That's what I've been working on for the past couple days. For some reason, the updates are super slow and in the end you can see pixels coming back after the screen was obviously cleared.

The updates were much faster before and the pixels didn't have this reversion problem - it just started happening out of nowhere earlier today and it persists across restarts. I haven't touched any part of the code that could possibly cause this. It started happening after I moved the event loop (of my program) to a different location, and moving it back didn't fix the problem.

I also have no idea how the cursor position affects this. Perhaps it's just the pixel updates in those rows? Because my cursor position is stored separately from the native term's.

**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - Version: 2.4.5
 - Compiled from source? No

**Additional context**
I know this isn't much to go on. I guess I'm just hoping that you know what might be causing this. Please let me know if you need additional info or the program itself.

**Comment by MCJack123** [comment]
Could you send me your code? It looks like the line buffers in your program aren't being fully erased when the screen's cleared, but I may be wrong.

**Comment by LoganDark** [comment]
@MCJack123 There are no line buffers at all. It just sets pixels, it doesn't remember anything. The only thing it remembers is the 6 pixels underneath the cursor which it restores when the cursor blinks off.

**Comment by LoganDark** [comment]
Was an intentional "feature" in the window api
