### ISSUE TITLE
Mounting relative paths

### ISSUE THREAD

**Issue by LoganDark** [MCJack123/craftos2#164]
**Is your feature request related to a problem? Please describe.**
You have to specify an absolute path to mount things, and I'd love to do `--mount-ro /build=build` or even `--mount-ro /build=~/cpc-dev/build`, but no, I have to do `--mount-ro /build=/Users/LoganDark/cpc-dev/build`

**Describe the solution you'd like**
I think these should be resolved from the CWD when the executable starts

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MCJack123** [comment]
Most of this should already be happening. Mounts don't explicitly specify absolute paths, so it's up to the OS to decide how to resolve it. From my testing, I've been able to use relative paths just fine* on both macOS and Windows.

However, being relative to the user home is a bit trickier. The shell is what resolves `~` to your user path, not the OS. Specifically, it will only resolve `~` when it's at the beginning of a string (IIRC), so when it's in the middle like in `/build=~/cpc-dev/build`, the shell doesn't expand it. In this case, you can use `$HOME` instead, which will expand it properly.

*I once had issues a long time ago where the `--script` flag would refuse to use relative paths. This seems to have gone away now, for some reason. I still have no idea why that was happening.

**Comment by LoganDark** [comment]
> Most of this should already be happening. Mounts don't explicitly specify absolute paths, so it's up to the OS to decide how to resolve it. From my testing, I've been able to use relative paths just fine* on both macOS and Windows.

That's weird. It hasn't worked for me. I mean, it did before but now it doesn't? Weirdness.

> you can use `$HOME` instead, which will expand it properly.

Yeah, that's what I ended up doing. I was under the impression that the OS did that, not the shell, but I guess I was wrong.
