### ISSUE TITLE
MacOs niche case inconsistent window switching issue

### ISSUE THREAD

**Issue by hugeblank** [MCJack123/craftos2#179]
**Describe the bug**
When in fullscreen and switching between multiple computer windows, rather than sticking to one window it'll slide over to a different window. It seems to obey chronological order, maybe PID order?

**To Reproduce**
1. Open one computer
2. Open another
3. Using a magic trackpad (or ctrl+arrow keys) navigate to the second computer
4. See inconsistency (or not)

**Expected behavior**
Stay on the window I tab into

**Screenshots**
[A video demonstrating the issue when it happens](https://streamable.com/x6rczs)

**Environment (please complete the following information):**
 - OS: Mac OS Big Sur
 - OS Version: 11.1
 - CraftOS-PC Version: v2.5
 - Compiled from source? [Yes]

**Additional context**
<img width="296" alt="image" src="https://user-images.githubusercontent.com/16393543/103436237-32a5b980-4bce-11eb-9b8c-f627b8daf5a1.png">
The start fullscreen option is false yet all windows I open are fullscreen, this might help narrow things down, not too sure.

**Comment by MCJack123** [comment]
This is a bug in SDL2. [I have reported it on the SDL Bugzilla.](https://bugzilla.libsdl.org/show_bug.cgi?id=5432)

**Comment by MCJack123** [comment]
It doesn't look like this will ever be fixed, so I'm closing it for now.
