### ISSUE TITLE
Crash when running program

### ISSUE THREAD

**Issue by hugeblank** [MCJack123/craftos2#182]
**Describe the bug**
crash when running specific code. When I hoist a function up outside a block of code that eventually becomes a block of coroutine. Perhaps that's the issue? That's all I can come up with.

**To Reproduce**
1. Download code from [here](https://github.com/hugeblank/KristChat/tree/craftos-debug)
2. Attempt running on latest version
3. See error

**Expected behavior**
If the reason it crashes is because of my code, a proper error should be spat out

**Environment (please complete the following information):**
 - OS: Mac OS
 - OS Version: 11.1
 - CraftOS-PC Version: v2.5.1
 - Compiled from source? Kinda - originally compiled from source, then updated to v2.5.1

**Comment by MCJack123** [comment]
Do you have any crash logs? Check the Console (in /Applications/Utilities) under the Crash Reports section in the sidebar.

**Comment by hugeblank** [comment]
LMAO I meant to link it: https://pastebin.com/nJ96SzP5

**Comment by hugeblank** [comment]
I must say, I wish I had your skill for fixing bugs so quickly
