### ISSUE TITLE
Unable to attach a printer peripheral

### ISSUE THREAD

**Issue by mlntcandy** [MCJack123/craftos2#183]
**Describe the bug**
Attaching a printer throws an error, both in the web version and standalone, even though the documentation and the `attach list` command say it is possible. 

**To Reproduce**
1. Open CraftOS-PC
2. Type `attach top printer` (the side doesn't matter, it fails anyway)
3. Press Enter

**Expected behavior**
Successful execution of the `attach` command and some sort of a GUI popping up.

**Screenshots**
![image](https://user-images.githubusercontent.com/31708294/103670840-300ae180-4f8b-11eb-822e-5aca8b4fd8aa.png)

**Environment (please complete the following information):**
 - OS: Ubuntu LTS 20.04 "focal" (KDE neon User Edition 5.20)
 - CraftOS-PC Version: v2.5.1.1
 - Compiled from source? [No]

**Additional context**

**Comment by LoganDark** [comment]
I think it wants a filename to print to.

**Comment by mlntcandy** [comment]
> I think it wants a filename to print to.

Ah, yes, now i see. It does. Not a bug.
But the way CC printers work is similar to displays, it prints in Minecraft font on a piece of paper, so i naturally thought this was going to bring up some sort of a window. I'll close this and open an issue as a feature request. Sorry for inconvenience and thank you.

**Comment by LoganDark** [comment]
> I'll close this and open an issue as a feature request.

You can use Lua to emulate a printer on a monitor. This doesn't need to be a CPC feature.
