### ISSUE TITLE
Editing ROM.

### ISSUE THREAD

**Issue by EmeraldImpulse7** [MCJack123/craftos2#187]
**Is your feature request related to a problem? Please describe.**
I want to load some programs on boot, like APIs, without having to use include.

**Describe the solution you'd like**
A rom folder in the CraftOS-PC directory, you can add files in it, and it will add them to the ROM, sort of like the Lua Resource Packs.

**Describe alternatives you've considered**
I guess you could just make the rom folder not read-only, but that kind of ruins the whole purpose of a ROM folder.

**Comment by MCJack123** [comment]
The ROM files are fully exposed in the installation folder (`C:\Program Files\CraftOS-PC\rom`) - it's trivial to just go into the ROM directory and add your own stuff. If you set `romReadOnly` to false in the config (dangerous; only available in `global.json`) you can also have the ROM be mounted read-write, meaning you can edit it from CraftOS. There's also the VFS functions in the plugin API, which are used by the CCEmuX plugin to add the `emu` command through adding an additional mount over `/rom`. Finally, you can use the `--rom` option to specify your own folder that contains `bios.lua` and `rom`, which is especially useful when making custom OSes.

Regarding loading APIs and programs on boot:
* Anything added to `rom/apis` is auto-loaded as an API. (Note that `os.loadAPI` is deprecated, and use of this folder should be minimized.)
* `rom/modules/main` can be used to add custom `require`able modules, as is used by `cc.expect` and others.
* Files in `rom/autorun` are automatically run on boot like `/startup`, so if you want something run at boot on all computers you can use that.
