### ISSUE TITLE
Compiling to macOS App: "Please build Lua for your platform inside the craftos2-lua directory." When it's already been built.

### ISSUE THREAD

**Issue by Psypherix** [MCJack123/craftos2#190]
**Describe the bug**
Make is confused as to why I didn't make craftos2-lua, when I did with the `make -C craftos2-lua macosx` command on step 4.

**To Reproduce**
1. `git clone https://github.com/MCJack123/craftos2`
2. `cd ./craftos2`
3. `git submodule update --init --recursive`
4. `make -C craftos2-lua macosx`
5. `./configure`
6. `make macapp`

**Expected behavior**
I should be able to get a macOS app of CraftOS-PC that uses the latest pull from the repo and then put in the CraftOS ROM into it. to continue the build.

**Screenshots**
<img width="710" alt="Screen Shot 2021-03-17 at 10 58 52 AM" src="https://user-images.githubusercontent.com/80654701/111488587-c4be5800-870f-11eb-8c26-cc436389cd1c.png">

Here's my exact console output and what I typed into it to get this error.
[consolelog.log](https://github.com/MCJack123/craftos2/files/6157399/consolelog.log)

**Environment (please complete the following information):**
 - OS: macOS Mojave 
 - OS Version: 10.14.6
 - CraftOS-PC Version: Latest from Github as of 3/17/2021
 - Compiled from source? Yes, attempting to, at least.

**Comment by MCJack123** [comment]
The makefile has been updated a bunch since this was created - hopefully it's fixed now. If not, feel free to reopen. Closing.
