### ISSUE TITLE
ROM: Pngview gets the wrong resolution

### ISSUE THREAD

**Issue by trollbreeder** [MCJack123/craftos2#195]
**Describe the bug**
`/rom/programs/fun/advanced/pngview.lua` errors with "Image is too big" because it's getting _text mode resolution_, not 256 color graphics resolution. This is because term.getSize(2) is called in **text mode** (line 627)

**To reproduce**
1. Open CraftOS-PC
2. Set your resolution to (text mode resolution) width 95, height 50
3. `wget https://media.discordapp.net/attachments/801961845057519657/825679492592828426/troll_labs.png troll_labs.png`
4. `pngview troll_labs.png`
5. Get error "Image is too big"

**To bodge a fix**
Steps to make a quick and dirty fix:
1. Open the folder where CraftOS-PC was installed to, then navigate to `rom/programs/fun/advanced/pngview.lua` and edit it
2. Jump to line 627 and surround it with `term.setGraphicsMode(2)` and `term.setGraphicsMode(0)`
3. As expected, the image renders properly and you should see the stylized text "Troll Labs"

**Expected behavior**
[with the sample image] The image renders properly and you should see the stylized text "Troll Labs"

**Screenshots**
Sample image:
![image](https://media.discordapp.net/attachments/801961845057519657/825679492592828426/troll_labs.png)
Normally:
![image](https://user-images.githubusercontent.com/25937686/112750204-8b1b0600-8fc7-11eb-82c6-01b40a4a073c.png)
Fixed with instructions from "To bodge a fix":
![image](https://user-images.githubusercontent.com/25937686/112750233-baca0e00-8fc7-11eb-858d-cb69f14061f8.png)

**Environment**
 - OS: Windows 10
 - OS Version: 1909
 - CraftOS-PC Version: v2.5.4-luajit
 - Compiled from source? No.

**Comment by MCJack123** [comment]
Fixed in MCJack123/craftos2-rom@2b3444798838d80ab3141384f9c1bcaa4811c790
