### ISSUE TITLE
Incorrect modulo result for negative dividend values

### ISSUE THREAD

**Issue by migeyel** [MCJack123/craftos2#196]
**Describe the bug**
The modulo `%` operator returns a non-standard value when the first argument is negative, even if `standardsMode` is set to true.

**To Reproduce**
1. Open the lua interactive prompt on a computer
2. Type `-2 % 2`

**Expected behavior**
The operation result should have been equal to 0.

**Screenshots**
![2021-04-03_02 50 49](https://user-images.githubusercontent.com/41488876/113469896-96d35600-9427-11eb-973a-09f8d48ef63f.png)

**Environment**
 - OS: Ubuntu
 - OS Version: 18.04.5 LTS
 - CraftOS-PC Version: v2.5.4
 - Compiled from source? No

**Comment by LoganDark** [comment]
This is incorrect. % is a modulo, not a remainder.
