### ISSUE TITLE
hiruste ppa

### ISSUE THREAD

**Issue by devomaa** [MCJack123/craftos2#197]
**Describe the bug**
PPA doesnt work on hiruste

**To Reproduce**
1. Update to Ubuntu hiruste prerelease
2. add your ppa
3. (update repos if for some reason doesnt do it already)

**Expected behavior**
PPA should have hiruste support

**Screenshots**
```
E: The repository 'http://ppa.launchpad.net/jackmacwindows/ppa/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Environment (please complete the following information):**
 - OS: [Ubuntu 21.04 hiruste]
 - OS Version: [e.g. 2020-2021]
 - CraftOS-PC Version: meta-issue
 - Compiled from source? meta-issue

**Additional context**
None

**Possible fix**
change hiruste to groovy in repo source file (hacky)

**Comment by MCJack123** [comment]
I was waiting for it to release fully, but it's not a problem to handle it earlier. (In fact, Groovy was added ahead of time by a lot.) I'll add Hirsute to the list of versions to build for, and a build will be available for v2.5.5 (which should be out within the next few days).
