### ISSUE TITLE
http.get() unencodes encoded forward slashes (%2F)

### ISSUE THREAD

**Issue by FatalMerlin** [MCJack123/craftos2#199]
**Describe the bug**
When making a `http.get()` call to a url that contains an url-encoded forward slash (%2F), the slash will be unescaped (/) when the request is being send.

Example URL:
https://gitlab.com/api/v4/projects/278964/repository/files/public%2Fdeploy.html?ref=master
This API expects url-encoded paths inside the repository, and returns 404 without the url-encoded slashes

**To Reproduce**
1. open lua prompt
2. `res,err = http.get("https://gitlab.com/api/v4/projects/278964/repository/files/public%2Fdeploy.html?ref=master")`
3. check `err`
4. check url in browser

**Expected behavior**
%2F should not be replaced or escape pattern should be escapable (e.g. with %252F => %2F)

**Screenshots**
![2021-04-23_09 54 02](https://user-images.githubusercontent.com/14237330/115838929-72f9a380-a41a-11eb-8e8a-69a469c4209e.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 20H2 Build 19042.928
 - CraftOS-PC Version: v2.5.5
 - Compiled from source? No

**Additional context**
I tried working around the decoding but %252F doesn't work (stays as is) and %%2F crashes CraftOS-PC.
This bug does not exist in CCEmuRedux. Unsure about ComputerCraft, couldn't test yet.

**Comment by FatalMerlin** [comment]
Hi, found the error, it's the Poco:URI library.

ref: https://github.com/MCJack123/craftos2/blob/57c0485ea0f98bd8a7724fa2fa1624bf172c7f65/src/apis/http.cpp#L370
see: https://pocoproject.org/docs/Poco.URI.html

```The class automatically performs a few normalizations on all URIs and URI parts passed to it:

scheme identifiers are converted to lower case
**_percent-encoded characters are decoded (except for the query string)_**
optionally, dot segments are removed from paths (see normalize())```

**Comment by SquidDev** [comment]
> Unsure about ComputerCraft, couldn't test yet.

Tested in CCEmuX (which is basically just CC) and can confirm it also isn't present there.

**Comment by FatalMerlin** [comment]
@SquidDev thanks for the quick test!

**Comment by FatalMerlin** [comment]
Unfortunately I'm neither a C++ nor a Poco expert so I'm not sure how to work around this issue.
Apparently Poco is only allowing encoded characters in the query string?
How could encoded characters be allowed in the the path of the url?

**Comment by FatalMerlin** [comment]
So the underlying issue is that Poco always decodes the path part of the URI, so once it encounters a % sign it decodes said character. However double encoding works in the latest version afaik / tested (%252F), because it only does one pass.

Maybe it would be sufficient to update poco? Unfortunately I can't get Poco Https to work so I can't check if the url path part gets altered again in the http request...

**Comment by FatalMerlin** [comment]
@SquidDev does CCEmuX also use Poco? How is it handled there?

**Comment by MCJack123** [comment]
This is indeed an upstream issue in Poco. I've reported it [on the Poco issue tracker](https://github.com/pocoproject/poco/issues/3256).

> 
> 
> @ SquidDev does CCEmuX also use Poco? How is it handled there?

CraftOS-PC uses a substantially different code base from most other CC emulators (being written in C++), and as such anything that isn't implemented in Lua can't be directly compared. Poco is a C++ library, and since CC and other emulators like CCEmuX are in Java they can't use it.

**Comment by FatalMerlin** [comment]
@MCJack123 okay, glad that's identified - I tried my best to reproduce in a CPP environment with very little understanding of CPP (am C# and TS dev).

However, in my test I noticed that %252F (so double encoding %2F) does work with poco, so the question is, why does it not work with CraftOS-PC? Can you update the library maybe? Or is it actually the HTTP code from Poco?

I tried to get the project to build on my machine but failed gloriously on setting up the cpp dependencies even with vcpkg... so I can't really check, however the crash with "%%25" happens because of an URLSyntaxException from Poco::Uri afaik.

Also, just want to say, I love your project and am extremely impressed by the quality and the features :)

**Comment by MCJack123** [comment]
I tried replacing all `%`s in the URL with `%25`, but it ended up re-encoding the string and sent `%252F` to the server. It handles other characters fine, obviously - it's just that it loses the fact that `%2F` should be re-encoded while constructing the `Poco::URI`.

In other news, I did fix the crash from passing invalid URLs. I should really go over the docs for everything and see what throws, as I've been mainly seeing crashes resulting from unhandled exceptions. As much as I get annoyed with Swift's mandatory exception handling, it makes things so much safer and I don't have to worry about these kinds of things.

**Comment by FatalMerlin** [comment]
Okay, maybe a stupid question and wayyy too much effort for this bug, but would it be possible to replace poco? Maybe with boost?

**Comment by MCJack123** [comment]
I used to use libcurl for HTTP stuff, but Poco is good because it has that plus WebSocket support. I also use it for JSON parsing, replacing jsoncpp. I might even start using the zip & PDF libraries at some point. I'm not going to replace it unless there's something seriously wrong that makes it impossible to continue using, and I haven't found anything near that, let alone a small bug in URL parsing. If it's that important, you could try adjusting `downloadThread` to grab the path portion from the original string instead of the `Poco::URI` object (I only use `Poco::URI` to handle splitting the components anyway).

**Comment by FatalMerlin** [comment]
I would love to make a fix here myself but I have trouble installing and setting up the project, and very little experience in the CPP toolchain.

**Comment by MCJack123** [comment]
Since Poco doesn't seem to be making any progress on their end, I decided to just take the path from the original string, passed through a simple URL encoder that won't re-encode the `%`s in the URL string. This should fix your issue.

**Comment by FatalMerlin** [comment]
Thank you @MCJack123 !
