### ISSUE TITLE
Vector2D index out of range

### ISSUE THREAD

**Issue by danilacasito** [MCJack123/craftos2#203]
**Describe the bug**
Worm.lua makes your computer crash

**To Reproduce**
1. Open CraftOS PC
2. Open worm.lua
3. Select Hard (because the error will show up more faster)
4. go to the right and wait until error shows up
**Expected behavior**
the worm is still moving

**Screenshots**
![imagen](https://user-images.githubusercontent.com/54474838/118396330-559dab00-b64f-11eb-8d53-63fe589dce7a.png)
**Environment (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - OS Version: [e.g. 2004] 20H2
 - CraftOS-PC Version: [e.g. v2.2] v2.5.5
 - Compiled from source? [Yes] [No] (if in doubt, choose No) No

**Additional context**

**Comment by MCJack123** [comment]
It looks like you're using some sort of shell/OS - if so, could you tell me what you're using? This bug may be triggered by that shell's drawing routine.
