### ISSUE TITLE
Opening a file only returns half the file.

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [MCJack123/craftos2#204]
**Describe the bug**
I don't actually know what the bug is, but when I open a *specific* file, in my case, `reactInstall.skimg`, it only returns half of the file. Using something like copycat returned the entire file.

**To Reproduce**
1. Download the file. `wget https://cdn.discordapp.com/attachments/477911902152949771/849289105447190568/reactInstall.skimg`
2. Open the Lua REPL
3. Enter these lines: `f = fs.open("reactInstall.skimg","r")`, `content = f.readAll()`, `f.close()`
4. Now, if you look at what's in `content`, you'll see it's only half the file.

**Expected behavior**
I expected it to read and return the entire file.

**Screenshots**
If applicable, add screenshots or recordings to help explain your problem. You can capture these using F2, F3, or F12. If CraftOS-PC has crashed, paste the stack trace here (wrapped in \`\`\` characters please!).
CraftOS-PC:
![image](https://user-images.githubusercontent.com/34724753/120342563-e6b68800-c2c5-11eb-843a-25f1681526f7.png)
CopyCat: (This is indeed the end of the file)
![image](https://user-images.githubusercontent.com/34724753/120342653-fd5cdf00-c2c5-11eb-91d7-c13aa77ace44.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 20H2
 - CraftOS-PC Version: 2.5.5
 - Compiled from source? No

**Additional context**
I was able to recreate the same thing on multiple CraftOS-PC computers (`attach 1 computer`)

**Comment by SkyTheCodeMaster** [comment]
I tried it in CCEmuX mounted to the same directory as CraftOS-PC computers, and it reads the file just fine
![image](https://user-images.githubusercontent.com/34724753/120380838-af5cd100-c2ef-11eb-9671-fbbd0401ac86.png)

**Comment by MCJack123** [comment]
Could you try running the console version and see if any message is reported in the window? Specifically, if there's an error saying "Error decoding UTF-8: ...".

**Comment by MCJack123** [comment]
I've been able to reproduce the issue - it only affects Windows systems. However, I can't get to my dev machine right now, so I'll have to debug this issue later.
