### ISSUE TITLE
Update to C++17

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#206]
C++17 brings some new features, including a shiny new `std::filesystem` library that will tremendously simplify the `fs` API, removing the need for many of the functions in the platform files. I considered this a while ago in #7, but decided that C++17 was a bit too new to be requiring for everything (this was in 2019). However, support has improved over the past two years, and all major compilers appear to support most of the features in C++17 now.

I think it's about time to switch over to C++17 and `std::filesystem` - that'll simplify things a lot and will probably reduce bugs too. At the same time, it might be wise to switch all of the file handle functions to use `istream`s too, since having two different versions of each function - one for `FILE*` and one for `istream` - makes it harder to keep track of bugfixes between functions for normal files and VFS files.

**Comment by Apethesis** [comment]
yeah but the main question is
will it make it faster
