### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by devomaa** [MCJack123/craftos2#208]
**Describe the bug**
Trying to run ./craftos segfaults.

**To Reproduce**
1. build craftos
2. add rom
3. run ./craftos

**Expected behavior**

**Screenshots**
OS: Linux
Address is (nil) from 0x7f2ca4338a64
Last C function: (none!)
[bt]: (1) /lib64/libc.so.6(_IO_feof+0x4) [0x7f2ca4338a64]
[bt]: (2) /lib64/libc.so.6(_IO_feof+0x4) [0x7f2ca4338a64]
[bt]: (3) ./craftos() [0x422a65]
[bt]: (4) ./craftos() [0x4ca3b6]
[bt]: (5) ./craftos() [0x4ca41d]
[bt]: (6) ./craftos() [0x4bdd08]
[bt]: (7) ./craftos() [0x4bda88]
[bt]: (8) ./craftos() [0x4bdb2b]
[bt]: (9) ./craftos() [0x4bef78]
[bt]: (10) ./craftos() [0x4bbd3e]
[bt]: (11) ./craftos() [0x4246c4]
[bt]: (12) ./craftos() [0x4292e7]
[bt]: (13) /lib64/libstdc++.so.6(+0xd9c84) [0x7f2ca46c2c84]
[bt]: (14) /lib64/libpthread.so.0(+0x9299) [0x7f2ca495a299]
[bt]: (15) /lib64/libc.so.6(clone+0x43) [0x7f2ca43bb353]
fish: Job 1, './craftos' terminated by signal SIGSEGV (Address boundary error)

**Environment (please complete the following information):**
 - OS: Fedora 34
 - OS Version: 2020
 - CraftOS-PC Version: bc8ebaa (source)
 - Compiled from source? Yes

**Additional context**
nothing

**Comment by MCJack123** [comment]
Try rebuilding from the latest commit - this fixed an issue that would likely cause a segfault.

**Comment by devomaa** [comment]
yeah, that doesnt work (same error, sorry for late response)
