### ISSUE TITLE
Error starting craftos

### ISSUE THREAD

**Issue by ViseTine** [MCJack123/craftos2#210]
**Describe the bug**
craftos is trying to start with Poco's outdated shared libraries

**To Reproduce**
1. Try starting craftos from the terminal 

**Expected behavior**
Start craftos

**Screenshots**
![error](https://user-images.githubusercontent.com/62775246/124510557-6f838080-ddaa-11eb-92d0-eea5f6140d71.png)
![lld](https://user-images.githubusercontent.com/62775246/124510575-7e6a3300-ddaa-11eb-8cf6-1cbb0b9753d2.png)

**Environment (please complete the following information):**
 - OS: ArchLinux
 - OS Version:
 - CraftOS-PC Version: 2.5.5-3
 - Compiled from source? [No]

**Additional context**
Poco's shared libraries are now .so.80

**Comment by MCJack123** [comment]
This can be resolved by reinstalling/clean-building the package (AUR packages are built from source). I've pushed an empty update to automate this.

**Comment by ViseTine** [comment]
That worked. Thanks!!
