### ISSUE TITLE
Pasting on android only ever pastes the first character of whatever you copied

### ISSUE THREAD

**Issue by GStudiosX2** [MCJack123/craftos2#217]
**Describe the bug**
Pasting only ever pastes the first character and also you can't access the clipboard

**To Reproduce**
1. Copy some text
2. Paste in ccpc on android
3. Only paste first character

**Expected behavior**
It's supposed to paste the full thing not just the first character also the clipboard doesn't show up but I don't really care about that

**Screenshots**
[Video](https://cdn.discordapp.com/attachments/795377444739219497/884919050034094160/screen-20210907-225207.mp4)

**Environment (please complete the following information):**
 - OS: android 11
 - OS Version: Friday july 30
 - CraftOS-PC Version: latest as of writing this
 - Compiled from source? No

**Additional context**
Not really it's just a small bug

**Comment by GStudiosX2** [comment]
Here's a video

**Comment by GStudiosX2** [comment]
Uploading screen-20210907-225207.mp4…

**Comment by MCJack123** [comment]
This will be remedied with a new dedicated paste button within the app. An alpha build of the new UI is available [on the website](https://www.craftos-pc.cc/nightly/CraftOS-PC-Android_09-20-21_18.22.apk) (or through TestFlight on iOS) - however, be aware that this build is unstable, so do not expect it to represent final quality.
