### ISSUE TITLE
[Suggestion] Ability to add mock peripherals

### ISSUE THREAD

**Issue by kirayatail** [MCJack123/craftos2#219]
I often use ComputerCraft to control peripherals like ExtremeReactors and various things with inventories (RF, fluids and items), and find craftOS-PC brilliant for developing and testing programs before deploying them into Minecraft.

I would like to have a solution for creating mocked peripherals that basically have arbitrary names and an attached set of functions that the peripheral exposes. I'm imagining something similar to mocked dependencies in unit testing libraries.

As an example: I have a program that monitors the level of a Thermal Expansion Energy Cell. The program is looking for attached peripherals like so: `local batteries = { peripheral.find('thermalexpansion:storage_cell')}`. If I were to run this program in a craftOS-PC for testing, I'd want to attach a mocked peripheral (namings are just a suggestion):

```
periphemu.createMock('back', 'thermalexpansion:storage_cell', {
    getRFStored = function() return 500 end,
    getRFCapacity = function() return 10000 end
})
```

When I then run my original program, it should pick up the mocked peripheral and be able to run the given functions.

**Comment by MCJack123** [comment]
This doesn't really seem like something that would fit into the core of CraftOS-PC: it's a bit too general and feels a bit hacky. However, I've made [a plugin](https://github.com/MCJack123/craftos2-plugins/blob/master/periphemu_lua.cpp) that implements this in a sane way, and should work well for your use case. The only caveat right now is that I needed to implement a new API function into CraftOS-PC to make it work; therefore, it will only be able to run on the next release (v2.6.2) and any dev builds starting today. If you want to test it out now, you can get the latest CI build [from the Actions tab](https://github.com/MCJack123/craftos2/suites/3888336211/artifacts/96889632).

**Comment by kirayatail** [comment]
I'm looking forward to that, and I'll look into plugins. Thank you for responding!
