### ISSUE TITLE
CraftOS-PC Online freezes randomly after some time

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#222]
**Describe the bug**
CraftOS-PC Online freezes at some point after starting. This is due to some sort of deadlock in the render thread, which should never happen but something in Emscripten is causing the lock to get stuck.

**To Reproduce**
1. Go to https://www.craftos-pc.cc/online/
2. Wait for CraftOS-PC to start up
3. Do some stuff
4. Notice that the screen freezes

**Expected behavior**
The screen does not freeze.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: All
 - OS Version: All
 - CraftOS-PC Version: Any since v2.5.?
 - Compiled from source? N/A

**Additional context**
This is a confusing issue because a) this deadlock shouldn't be possible, and b) it didn't happen in previous versions. In addition, I currently cannot update Emscripten to any version later than 2.0.4 due to a weird bug in `longjmp` that affects ONLY craftos2-lua running in a separate thread (emscripten-core/emscripten#13166). This is going to be tough to get past, but hopefully in the future once LLVM/Emscripten gets support for exception `longjmp`s (emscripten-core/emscripten#14976), I'll be able to upgrade and then see if the freezing issue is fixed as well.

**Comment by MCJack123** [comment]
A new update to Emscripten may have resolved this issue. I'm working on testing it more long-term to verify the fix.

**Comment by Mythical-Forest-Collective** [comment]
Is this gonna be fixed any time soon? Since Copy Cat doesn't work well at all rip

**Comment by MCJack123** [comment]
This should now be resolved with the latest update to the website. Please test to make sure it doesn't eat up memory anymore.
