### ISSUE TITLE
Crash on resize

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#225]
**Describe the bug**
Sometimes, when resizing CraftOS-PC, it throws an X11 protocol error and crashes.

**To Reproduce**
1. Launch CraftOS-PC from the command-line.
2. Grab the bottom-right corner of the window, and move the mouse cursor in circles.
3. See error

**Expected behavior**
I expect CraftOS-PC to not crash.

**Screenshots**
This is all the error information it gives.
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x1ac
  Serial number of failed request:  1281
  Current serial number in output stream:  1282
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - OS Version: N/A
 - CraftOS-PC Version: v2.6.2
 - Compiled from source? Yes (from AUR)

**Additional context**
I'm running CraftOS-PC in XWayland under Plasma Wayland, if that helps;  I believe I've come across this issue under X11 also.

**Comment by MCJack123** [comment]
Are you using the hardware renderer? When resizing, the renderer context gets invalidated and has to be regenerated; this is not easy to detect since it may happen in the middle of rendering, and the resize event has to be sent to the renderer before it attempts to call any rendering function on the context. I try to make it as unlikely as possible for it to crash while resizing, but in certain tight circumstances it's still possible to crash it.

**Comment by Ocawesome101** [comment]
No, I am not using the hardware renderer.

When using SDL's native wayland mode, resizing is horribly slow and
stuttery but doesn't cause a crash.

**Comment by pjalsGit** [comment]
I also got this, it also had some weird aspect-ratio-resize thing, but it didn't obey aspect ratio at all.

**Comment by MCJack123** [comment]
Alright, so I finally managed to get an error similar to this, and I decided to "fix" it by just ignoring errors (printing them to console without exiting). Hopefully this doesn't cause many issues, but if there's a critical error in X11 then it'll have to crash spectacularly to stop itself.
