### ISSUE TITLE
fs.copy (and possibly other fs functions) see \26 as end of file

### ISSUE THREAD

**Issue by LinearNoodle** [MCJack123/craftos2#226]
Hello, for a while now the LevelOS dev build stopped working in CraftOS-PC and I've finally narrowed down the exact issue. Character 26 in CCs font is seen as end of file by CraftOS-PCs fs.copy (and possibly other functions, haven't tested). fs.open -> readAll handles it fine though.

The expected behaviour, just like what readAll does, is for it to just read the entire file instead of stopping at that character. This is also the behaviour in CCEmuX and ComputerCraft: Tweaked. The current behaviour is that it just cuts off at that character and thinks it successfully coppied the entire file.

I've currently created a workaround for LevelOS that replaces fs.copy with a custom function that uses fs.open to read the file's contents and write them into the new location, but a permanent and global solution is needed.
![](https://media.discordapp.net/attachments/798410292236779550/912363894142554122/unknown.png)
In this image I have created a file with the character in it, then I copied it and the second file is the result. As you can see it cuts off at the arrow (character 26).

EDIT: I'm using Windows 10, latest version of CraftOS-PC.

**Comment by MCJack123** [comment]
Related: #204
