### ISSUE TITLE
Computer viewports flash when running

### ISSUE THREAD

**Issue by Hasaabitt** [MCJack123/craftos2#227]
**Describe the bug**
The viewport flashes in all computer windows

**To Reproduce**
1. Launch program
2. See error

**Expected behavior**
The viewport should not be flashing

**Screenshots**
![2021-11-30-15-57-31](https://user-images.githubusercontent.com/50884531/144127789-0fd0eaec-be21-44a4-9b70-0c99b22396b4.gif)

Disregard the visual artifacts

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H2
 - CraftOS-PC Version: 2.6.2

**Comment by MCJack123** [comment]
1. Do you have hardware rendering enabled? (Open `%appdata%\CraftOS-PC\config\global.json` and look for `useHardwareRenderer`.)
2. What GPU do you have?

**Comment by Hasaabitt** [comment]
1. `useHardwareRenderer` is enabled
2. My GPU is a NVIDIA GeForce GTX 1660 SUPER

**Comment by Ocawesome101** [comment]
Does disabling the hardware renderer fix this?

**Comment by VladTheEvilCat** [comment]
Had same exact issue, disabling hardware renderer fixed it right up!
