### ISSUE TITLE
iOS Gestures Broken or Outdated Documentation

### ISSUE THREAD

**Issue by FayneAldan** [MCJack123/craftos2#230]
**Describe the bug**
The gestures on the iOS version, as explained by the `help gestures` command, don’t seem to work.

**To Reproduce**
1. Type `help gestures`
2. Observe the described gestures
3. Attempt to perform any of the gestures with two fingers, as the documentation says

**Expected behavior**
The gestures work as described in the documentation.

**Screenshots**
![](https://user-images.githubusercontent.com/1149870/146675881-ef7c0a60-3868-4a0d-91ed-3c16e67aa6e8.jpeg)

**Environment (please complete the following information):**
 - OS: iOS
 - OS Version: iOS 15.2
 - CraftOS-PC Version: 2.6.3
 - Compiled from source? No

**Additional context**
The only gesture that seems to do anything is **single** tapping the screen with to fingers to open up the window switcher, which isn’t even documented in `help gestures`. I’m not sure if this behavior is due to an actual bug or if the gestures were intentionally removed but the documentation is outdated.

**Comment by MCJack123** [comment]
This has been fixed in MCJack123/craftos2-rom@17fe9e5d160d336b65a9ab46c19eb231c4412419.
