### ISSUE TITLE
iPad: Keyboard input breaks after switching apps

### ISSUE THREAD

**Issue by FayneAldan** [MCJack123/craftos2#231]
**Describe the bug**
Most keyboard inputs break after switching apps and going back into CraftOS-PC.

**To Reproduce**
1. Close OpenOS-PC if it’s already open.
2. Open CraftOS-PC.
3. Go to the iPad home screen without closing CraftOS-PC.
4. Re-open CraftOS-PC, either through the home screen icon or from the app switcher.

**Expected behavior**
Keyboard continues working as normal.

**Screenshots**
https://cdn.discordapp.com/attachments/795377444739219497/922204257095122974/RPReplay_Final1639940933.mov

**Environment (please complete the following information):**
 - OS: iPad OS
 - OS Version: 15.2
 - CraftOS-PC Version: 2.6.3
 - Compiled from source? No

**Additional context**
This happens with both the on-screen keyboard and a physical keyboard. It does not happen on iPhone, only on iPad.

**Comment by MCJack123** [comment]
This will be fixed in the next update. For now, if this happens again please close and re-open the keyboard using the button in the navigation bar.
