### ISSUE TITLE
ipad keyboard case support

### ISSUE THREAD

**Issue by Arbee4ever** [MCJack123/craftos2#232]
**Describe the solution you'd like**
I would like to use my keyboard case (which also has arrow keys, tab and stuff) to type in this app.

**Describe alternatives you've considered**
At this moment, none.

**Additional context**

**Comment by FayneAldan** [comment]
This is caused by #231. I use the iPad keyboard case but it stops working if you switch apps and go back.

**Comment by Arbee4ever** [comment]
This happens to me directly after I started the app.

**Comment by MCJack123** [comment]
Make sure the toolbar at the bottom with the extra keys, as well as the keyboard options & dictation buttons, are visible at the bottom. If not, tap the screen with two fingers and press the open keyboard button at the top.

**Comment by MCJack123** [comment]
I've been using CraftOS-PC on my iPad with Magic Keyboard for many months and it's been working fine. Reopen this if you still have problems.
