### ISSUE TITLE
Execution time for taking substrings depends on input size

### ISSUE THREAD

**Issue by migeyel** [MCJack123/craftos2#233]
**Describe the bug**
The time taken to take a substring (or decode a value using `string.unpack`) depends on the size of the input.

**To Reproduce**
1. Measure how long it takes to call `sub` on a small string.
2. Measure how long it takes to call `sub` on a large string, using the same output length.

**Expected behavior**
- The time taken by `sub` to either be constant or depend solely on output size.
- The time taken by `unpack` to depend solely on output size.

**Screenshots**
![Screenshot_2022-01-08_11-22-38](https://user-images.githubusercontent.com/41488876/148647904-85b79258-2054-4eca-8be7-eda2803d1696.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - CraftOS-PC Version: v2.6.4
 - Compiled from source? Yes (AUR)

**Comment by Ocawesome101** [comment]
I think this is something that happens in standard Lua.  I’ll test it later with a couple different Lua versions to make sure.

**Comment by MCJack123** [comment]
This is not possible, as `string.sub` is an O(1) algorithm: it just allocates a new object with the original string + offset and length, and adds it to the GC chain. There must be some side effect somewhere causing this - potentially the lack of locals in the test?

https://github.com/MCJack123/craftos2-lua/blob/521ba232a5475b54b8a046026a6d714786b475a2/src/lstrlib.c#L56-L67
https://github.com/MCJack123/craftos2-lua/blob/521ba232a5475b54b8a046026a6d714786b475a2/src/lapi.c#L531-L562

**Comment by migeyel** [comment]
I've possibly found the issue. It turns out that if `s` is a rope then `s:sub` will resolve the rope in O(n). However, `s` remains being a rope so every further operation on it always takes O(n) to perform.

The following modified test goes through with no issues:
```lua
-- test2.lua
for i = 7, 9 do
    local s = tostring(("a"):rep(10 ^ i)) -- Resolve the rope before taking the substring.
    local t0 = os.clock()
    local _ = s:sub(1, 10)
    print(os.clock() - t0)
end
```

Cobalt seems to solve this by using an extra string attribute so that resolving the same rope again takes O(1) time.

**Comment by MCJack123** [comment]
Hm, I didn't realize the auxlib buffer API used `lua_concat` internally, so I figured `string.rep` was returning a normal string. The idea to store the generated string in the rope is good, so I'll implement that.

**Comment by MCJack123** [comment]
I also refactored `string.rep` to write everything to a buffer first - this matches the behavior of Cobalt. This should remove any rope confusion from that one function.
