### ISSUE TITLE
there is no `cc.audio.dfpwm`

### ISSUE THREAD

**Issue by walksanatora** [MCJack123/craftos2#236]
**Is your feature request related to a problem? Please describe.**
get `cc.audio.dfpwm` library from computer craft as it is not in the current version of the CraftOS-PC

**Describe the solution you'd like**
just update the data to include cc.audio.dfpwm from [https://github.com/cc-tweaked/CC-Tweaked/tree/mc-1.16.x/src/main/resources/data/computercraft/lua/rom/modules/main/cc/audio](https://github.com/cc-tweaked/CC-Tweaked/tree/mc-1.16.x/src/main/resources/data/computercraft/lua/rom/modules/main/cc/audio)

**Describe alternatives you've considered**
this is just importing a library that has not been brought over

**Additional context**
tired of aukit erroring

**Comment by MCJack123** [comment]
Please make sure you are on v2.6.4. `cc.audio.dfpwm` has existed in [the ROM](https://github.com/MCJack123/craftos2-rom/blob/master/rom/modules/main/cc/audio/dfpwm.lua) since December 23, two days before release.

**Comment by walksanatora** [comment]
then it has not updated in the `apt` repository because the latest version in apt does not include the `cc.audio.dfpwm` library

**Comment by MCJack123** [comment]
I've re-synced the packages for focal and impish. If you're on hirsute, you'll have to update to impish (which you can't really do anymore).
