### ISSUE TITLE
craftos: error while loading shared libraries: craftos2-lua/src/liblua.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by walksanatora** [MCJack123/craftos2#237]
**Describe the bug**

getting `craftos: error while loading shared libraries: craftos2-lua/src/liblua.so: cannot open shared object file: No such file or directory`
when running from outside the folder

**To Reproduce**
build the craftos pc binary with `make` (i ran with `-j4` for using all 4 of my cores)
head to another folder
try to run the binary either via a relative path or a symlink to the craftos binary

**Expected behavior**
the liblua should either be built in or be able to be resolved instead of from the local path

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10] Linux Mint 20
 - OS Version: [e.g. 2004] (this can be found in Settings -> System -> About) 
 - CraftOS-PC Version: [e.g. v2.2] v2.6.4
 - Compiled from source? [Yes] [No] (if in doubt, choose No) yes

**Comment by MCJack123** [comment]
This is due to how the build process works. You need to use the `patchelf` utility to change the path it looks for the library at, then make a link next to the executable:
```sh
patchelf --replace-needed craftos2-lua/src/liblua.so libcraftos2-lua.so craftos
ln -s craftos2-lua/src/liblua.so libcraftos2-lua.so
```
I can't make this happen automatically, as `patchelf` is platform-specific and is not universal across Linux distros.

**Comment by walksanatora** [comment]
mabey do something like this during the `craftos` target
[https://stackoverflow.com/a/34756868/14969319](https://stackoverflow.com/a/34756868/14969319)
(only execute the patchelf step if patchelf is on path)

**Comment by walksanatora** [comment]
(i am testing locally and making a `patchelf` target that includes the patchelf fix)

**Comment by walksanatora** [comment]
[patchelf_target.patch](https://github.com/MCJack123/craftos2/files/8011781/patchelf_target.patch.txt)
a simple patch that patches `Makefile.in` to add the `patchelf` target which also runs the `craftos` target
(and adds to the `clean` target to remove the symlink to the lib)

**Comment by walksanatora** [comment]
should i pr this patch into the main repo as a extra target (also there are some cases where you refrence the `craftos` target directly instead of using `@OUT_TARGET@`)

**Comment by khankul** [comment]
Same issue with the AppImage. Can't compile from source for now, so it prevents me from using the software. I suppose this should get fixed.
