### ISSUE TITLE
[iOS] using any multi-finger gestures causes a crash

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#238]
**Describe the bug**
Under iOS, when I try to use any gestures for anything using more than one finger, the emulator crashes almost instantly. 

**To Reproduce**
1. Open CraftOS-PC Mobile
2. Swipe anywhere with two fingers
3. Probably observe crash

**Expected behavior**
No crash. 

**Environment (please complete the following information):**
 - OS: iOS
 - OS Version: 15.3.1
 - CraftOS-PC Version: 2.6.4 (apparent latest in the beta)
 - Compiled from source? No

**Additional context**
I'm running CraftOS-PC on an iPhone SE first generation.

**Comment by Ocawesome101** [comment]
Update: this does not happens every time. I'm not sure why.

**Comment by MCJack123** [comment]
This is a known issue, and I've been trying to track it down for months, but it's nasty in that it doesn't appear when a debugger is attached and is very hard to reliably reproduce otherwise.

**Comment by Ocawesome101** [comment]
i believe this can be closed.
