### ISSUE TITLE
Improper handling of # fragment in URLs

### ISSUE THREAD

**Issue by xAnavrins** [MCJack123/craftos2#239]
**Describe the bug**
When doing http/websocket requests with urls containing an `#` fragment, the fragment is still being sent when it should not be.
![Wireshark_m2I9p3kQen](https://user-images.githubusercontent.com/5376823/154965415-d10bb735-9022-4645-80bd-b81c30a4051e.png)

**Expected behavior**
`#` fragments shouldn't be included in the http request, but should still be tracked internally.
![CraftOS-PC_y39YYfyN1Q](https://user-images.githubusercontent.com/5376823/154967254-9e2fb2fb-4edb-4435-a376-6cd0dc16ec6d.png)

**Environment:**
 - OS: Windows 10
 - CraftOS-PC Version: v2.6.5
 - Compiled from source?: No

**Comment by MCJack123** [comment]
This is already fixed in 4387d7bd1f894e3950bd5b57d6e8645c0f5b9d28.

**Comment by xAnavrins** [comment]
Fixed for http requests, but it is still happening with websockets.
