### ISSUE TITLE
My program does not work :(

### ISSUE THREAD

**Issue by ajh123** [MCJack123/craftos2#241]
**Describe the bug**
My operating system for Computer Craft does not run properly 

**To Reproduce**
1. Go to 'https://github.com/ajh123-development/gtmos-cc' and clone it on to a CraftOs-PC.
2. Start the startup file somehow
3. See error

**Expected behavior**
![os](https://user-images.githubusercontent.com/41990982/157113099-47ae12b1-644f-4180-a730-04fa9de2f9ca.PNG)
Minecraft 1.18.1 CC Tweaked 1.100.2

**Actual outcome**
![os2](https://user-images.githubusercontent.com/41990982/157113339-21b68d9b-2946-4e1c-a863-dcc8008fabb6.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - OS Version: 21H2
 - CraftOS-PC Version: v2.6.5.1
 - Compiled from source?  [No]

**Additional context**
It may be some of my LUA but any fix would be good.

**Comment by MCJack123** [comment]
I see no clear error here, besides one window not being open. I'm not going to debug your program for you. If you can come up with a *specific* thing that is causing whatever is wrong to happen (in other words, a function that is not working correctly), you may reopen this issue, and explain what is wrong and why this is happening.
