### ISSUE TITLE
`string.rep` with a negative number results in `not enough memory`

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#247]
**Describe the bug**
Passing a negative number to `string.rep` causes a `not enough memory` error.  In both regular Lua and in CCEmuX it does not do this.

**To Reproduce**
1. Run `lua`
2. Enter `string.rep(" ", -3)`
3. Press `[Enter]`

**Expected behavior**
`string.rep` should return a string of length 0.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - OS Version: N/A
 - CraftOS-PC Version: 2.6.6
 - Compiled from source? Yes (AUR, v2.6.6-1)

**Additional context**
Initially discovered in DoT OS.

**Comment by MCJack123** [comment]
So this is what was causing the memory allocation errors. Fixed in MCJack123/craftos2-lua@a8c519a01cd42aab1576d49df943dfda312e6a1e
