### ISSUE TITLE
Too long without yielding when holding titlebar (on windows)

### ISSUE THREAD

**Issue by 1Turtle** [MCJack123/craftos2#248]
**Description**
CraftOS returns a error when holding the window titlebar _(to like move it)_ for a longer time with some programs running _(and others not)_.
When doing with `worm`, it returns the error message: `/.../worm.lua:227: Too long without yielding`
But I also was able to crash the whole OS! _(see screenshots)_

**To Reproduce**
1. Run `worm` program in CraftOS-PC
2. Hold titlebar with left-click & wait for about 4-15 seconds
3. See error

**Expected behavior**
Not a error message.

**Additional context**
I testet the same behavior with other programs like my editor _(1Turtle/consult)_ and it returned the error message: `bios.lua:179: Too long without yielding` _(as you can see in the screenshots)_
But then, the standard editor by dan works perfectly well.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/53350357/169885841-790da0e6-74a8-4276-8bfe-db065ee3a2c0.png)
![grafik](https://user-images.githubusercontent.com/53350357/169886026-c8a841b5-e315-4009-aad8-8b618fb380b3.png)
![grafik](https://user-images.githubusercontent.com/53350357/169884749-1c7d3eac-2956-4664-83e6-2cd9a2b357b5.png)

**Environment:**
 - OS: **[Windows 11 Pro]**
 - OS Version: **[21H2]**
 - CraftOS-PC Version: **[v2.2.0]**
 - Compiled from source? **[No]**

**Comment by Ocawesome101** [comment]
2.2.0 is a fairly old version at this point.  Have you reproduced this bug with v2.6.6?

**Comment by MCJack123** [comment]
This is because `os.startTimer` requires a main thread task, but Windows blocks the main thread when moving the window. I cannot fix this, so you'll have to deal with it.
