### ISSUE TITLE
--args flag not passing arguments to script

### ISSUE THREAD

**Issue by 99-lives** [MCJack123/craftos2#250]
**Describe the bug**
The --args flag doesn't seem to be passing the arguments to the script, when run with --headless and --script

**To Reproduce**
1. Create test file test.lua:
```
print(arg[1])
os.shutdown()
```
2. Run `craftos --headless --script test.lua --args "Hello!"`
3. Result:
```
CraftOS 1.8
View the documentation at
https://wiki.computercraft.cc
nil
```
**Expected behavior**
```
CraftOS 1.8
View the documentation at
https://wiki.computercraft.cc
Hello!
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - OS Version: N/A
 - CraftOS-PC Version: v2.6.6
 - Compiled from source? No, [AUR package](https://aur.archlinux.org/packages/craftos-pc)

**Comment by MCJack123** [comment]
The `arg` table is not supported in Lua 5.1 - it is deprecated in the shell, but not removed yet. Please use 5.1's `...` syntax for varargs instead.

```lua
-- test.lua
local args = {...}
print(args[1])
os.shutdown()
```

**Comment by 99-lives** [comment]
My mistake lol, thanks. `arg` does work when I run the script from within a running CraftOS computer, but not when running it with --script, so that was tripping me up. Cheers.
