### ISSUE TITLE
Attach drive freeze

### ISSUE THREAD

**Issue by scmcgowen** [MCJack123/craftos2#252]
**Describe the bug**
When in Full screen, attach [side] drive [path] freezes CraftOS-PC and doesn’t allow you to click allow.

**To Reproduce**
1. Press F11
2. run attach right drive [path]
3. Attempt to click yes or no

**Expected behavior**
You can click allow or deny as normal on the message box

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H1
 - CraftOS-PC Version: 2.6.6
 - Compiled from source? [No]

**Additional context**
done in LevelOS shell app

**Comment by MCJack123** [comment]
This is an issue in SDL (libsdl-org/SDL#5509), and was fixed in 2.0.22. The next release will include the fix.
