### ISSUE TITLE
Android bug with terminal

### ISSUE THREAD

**Issue by DanielMo09** [MCJack123/craftos2#253]
Hello,
I tried the version on android and ive got an bug. When i press the terminate, shutdown or restart button, it doesnt work, even tough i expect it to terminate, shutdown or reboot.

**Environment:**
 - OS: Android
 - OS Version: 11
 - CraftOS-PC Version: v2.6.6
 - Compiled from source: Yes

**Comment by MCJack123** [comment]
You need to hold the red buttons down just like in ComputerCraft. I apologize for this being unclear at first, and I'm looking for better ways to point this out in the UI.

**Comment by DanielMo09** [comment]
Thanks for the info.
