### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by DanielMo09** [MCJack123/craftos2#254]
Hello, i have found an bug on Android: Sometimes for me the app crashes randomly, but if it happens once it always happens. If u reinstall the app, the bug disappears. Now it happend 2 times for me.

**Environment:**
 - OS: Android
 - OS Version: 11
 - CraftOS-PC Version: 2.6.6
 - Compiled from source? Yes

Edit: reinstalling now doesnt work anymore, i dont know what to do now

**Comment by MCJack123** [comment]
I've pushed a beta build to Google Play testing that may fix this issue. You can enroll at https://play.google.com/apps/testing/cc.craftospc.CraftOSPC, and let me know if this fixes the issue.

**Comment by DanielMo09** [comment]
This worked I think, thank you very much!
