### ISSUE TITLE
CraftOS macOS does not allow secure connections

### ISSUE THREAD

**Issue by ale-ben** [MCJack123/craftos2#256]
**Describe the bug**
CraftOS 2.6.6 on macOS, installed via dmg from the website, fails when trying to do safe connections to the web.
Issue detected on both pastebin and wget

**To Reproduce**
- pastebin get nthk0sCy (or any other pastebin)
- get https://www.google.com (or any other https website) 

**Environment (please complete the following information):**
 - OS: MacOS Monterray 12.4
 - OS Version: Monterrey 12.4
 - CraftOS-PC Version: v 2.6.6
 - Compiled from source? No

**Additional context**
Tried the same commands on the iOS version and they work.

![Screenshot 2022-06-27 at 18 30 14](https://user-images.githubusercontent.com/17771264/175990104-39f0e5d0-2bba-4cd8-b1c2-a5ee48f11983.png)

**Comment by ale-ben** [comment]
![Screenshot 2022-06-30 at 12 14 25](https://user-images.githubusercontent.com/17771264/176652996-ee15f187-eedb-4290-89c9-3d3f65947214.png)

Interestingly enough, v2.6.5 does not generate this problem

**Comment by MCJack123** [comment]
This was fixed in be38d70cc6e95fee97129e3d9758eb3d8bcfaffc. Please wait for the next update - use v2.6.5 until then.
