### ISSUE TITLE
Improve documentation of functions: combine function reference with feature docs

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#262]
**Is your feature request related to a problem? Please describe.**
The API reference page of the website is not very well placed, hard to get to, and isn't linked to the pages that properly describe what they do. This makes figuring out how they work much more difficult. In addition, the reference comments aren't descriptive enough to provide much benefit outside of saying they exist.

**Describe the solution you'd like**
Combine the information on the API Reference with the pages for each feature, and list all of the relevant functions on each page. Also, rewrite the info text to be a bit more descriptive of what each parameter does.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Apethesis** [comment]
should dev happen
add it to the 2.7.3 milestone
or 2.7.4
