### ISSUE TITLE
Ubuntu 22.04.1 craftos-pc-data is not installable

### ISSUE THREAD

**Issue by Baa14453** [MCJack123/craftos2#269]
**Describe the bug**
Hi, when adding the PPA and installing the `craftos-pc` package it fails because it cannot install it's dependency `craftos-pc-data`

**To Reproduce**
1. Run Ubuntu 22.04
2. Add the PPA `sudo add-apt-repository ppa:jackmacwindows/ppa`
3. Run update `sudo apt-get update`
4. Try to install `sudo apt install craftos-pc`
```
$ sudo apt install craftos-pc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 craftos-pc : Depends: craftos-pc-data (>= 2.5) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Expected behavior**
Installation would complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/9057997/187025911-426bc147-b695-4d23-a1f7-f609701e9d49.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - OS Version: 22.04.1
 - CraftOS-PC Version: `1:2.7-jammy3`
 - Compiled from source? No

**Additional context**

**Comment by MCJack123** [comment]
I had to emergency pull the v2.7 ROM package due to some critical build issues, and I didn't have time to republish the old version. I've just gone ahead and requested a republish, and the package should be available within the next 30 minutes.

**Comment by Baa14453** [comment]
Thanks
