### ISSUE TITLE
Crash occurs when attempting to type "config" in shell

### ISSUE THREAD

**Issue by Hasaabitt** [MCJack123/craftos2#273]
**Describe the bug**
When attempting to type "config" into the shell to run the command, the computer crashes. Specifically, the crash occurs when typing the n. This is consistent across attempts. This does not occur when attempting to type config anywhere. (This includes lua REPL and in programs such as edit)

**To Reproduce**
1. attempt to type "config" in shell

**Expected behavior**
The command should run without crashing the computer

**Screenshots**
![image](https://user-images.githubusercontent.com/50884531/188245883-71baa554-1953-428c-a2e0-44dcd7525af8.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H2
 - CraftOS-PC Version: 2.71
 - Compiled from source? No

**Additional Context:**
I'm not sure if this relevant to this bug specifically, but it did hang once and created a crash dump
[CraftOS-PC.exe.13812.zip](https://github.com/MCJack123/craftos2/files/9481478/CraftOS-PC.exe.13812.zip)

**Comment by MCJack123** [comment]
Does this happen on a clean directory? (Run it with `-d %localappdata%\Temp` to use a temp directory) If not, try moving/deleting some files until it doesn't happen anymore, and let me know what causes it.

**Comment by Hasaabitt** [comment]
Ran with the data directory set in Temp as you said and it still crashes the same

**Comment by EmmaKnijn** [comment]
Made a duplicate issue accidentally, #280
