### ISSUE TITLE
mouse_move behaviour feels broken

### ISSUE THREAD

**Issue by NoryiE** [MCJack123/craftos2#276]
**Describe the bug**
The mouse_move event is sometimes stuttering and more problematic, sometimes it stops completely.

**To Reproduce**
1. Start CraftOS-PC activate mouse move by setting throttle amount (i used 10 for testing purpose)
2. Create a program with while true do print(os.pullEvent()) end in it and start it
3. Move the mouse cursor around for a while. Sometimes it stutters, sometimes it completly stops working

**Expected behavior**
Of course, I expect it to be consistent no matter how long I move the cursor

**Video**
Here is a video uploaded on streamable: https://streamable.com/2eh6bn

**Environment (please complete the following information):**
 - OS: Windows 11
 - OS Version: 21H2
 - CraftOS-PC Version: v2.7.1
 - Compiled from source? no

**Additional context**
You can see some heavy stuttering on 1:25. Around 1:47 it just stopped working, i have to click into the window again in order to make it work. Around 2:02 you will already see the next stop. In 2:28 you see it again, this time i try to move the cursor out of the window, which seems to work. I dont think this behaviour is supposed to be?

I dont know if i can do something myself to make this work consistently. If theres something i can do, let me know!
And btw, thanks for the awesome work!

**Comment by fatboychummy** [comment]
I am getting this issue as well in #318. Didn't realize an issue was already opened for this.
