### ISSUE TITLE
CraftOS-PC crashes assumingly due to CloudCatcher.

### ISSUE THREAD

**Issue by Apethesis** [MCJack123/craftos2#279]
**Describe the bug**
CraftOS-PC suddenly crashes after about 2 seconds of cloudcatcher use.

**To Reproduce**
1. Use cloudcatcher
2. Error

**Expected behavior**
I expected CraftOS-PC to not crash after 2 seconds.

**Screenshots**
![image](https://user-images.githubusercontent.com/86126617/191310336-8384ea0b-5b55-43d6-8888-f96f6920c6a3.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 10.0.19044 Build 19044
 - CraftOS-PC Version: v2.6.6
 - Compiled from source? No

(zip cause .dmp isn't supported)
[CraftOS-PC.exe.16064.zip](https://github.com/MCJack123/craftos2/files/9609511/CraftOS-PC.exe.16064.zip)

**Comment by MCJack123** [comment]
This should be fixed after the #297 and/or ping fixes. Reopen if it continues.
