### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Wileybot2004** [MCJack123/craftos2#283]
**Describe the bug**
uncaught exception causes program crash

**To Reproduce**
1.open craftOS-PC
2.type con(trying to type config)
3.have program crash

**Expected behavior**
open config

**Screenshots**
If applicable, add screenshots or recordings to help explain your problem. You can capture these using F2, F3, or F12. If CraftOS-PC has crashed, paste the stack trace here (wrapped in \`\`\` characters please!).
![image](https://user-images.githubusercontent.com/72325805/195914667-2d042ee3-beb6-4de8-ba36-21318bd49b52.png)
**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H2
 - CraftOS-PC Version: 2.7.1
 - Compiled from source? no

**Additional context**

**Comment by Ocawesome101** [comment]
fairly sure this has been fixed but isn't in a release yet (unless 2.7.2 is out).

**Comment by MCJack123** [comment]
Please explain what you were doing when this happened, and how to trigger it. I have no idea how to help you without knowing that.
