### ISSUE TITLE
Multitouch support for CraftOS-PC Mobile

### ISSUE THREAD

**Issue by LinearNoodle** [MCJack123/craftos2#285]
Hello! It is currently impossible to use multiple fingers to touch the screen in CraftOS-PC and have it properly register. When you have one finger touching the screen, touching it with other fingers simply does not queue any events. This makes developing intuitive programs for CraftOS-PC Mobile quite difficult.

My question would be if it would be possible to add multi-touch support. Even something as simple as having all fingers that touch the screen give off events would work, but it would be even better to for example use the mousebutton parameter in mouse events to indicate which "finger" touched the screen (which would just be an ID of tracked touch point).

This functionality would allow for awesome stuff being possible like recognizing things such as panning or making touch based games with joysticks and buttons that can be pressed at the same time.

**Comment by MCJack123** [comment]
I have added new events for multi-touch gestures: the `_CCPC_finger_tap`, `_CCPC_finger_up`, and `_CCPC_finger_drag` events will now be fired whenever a finger touches the screen. All of these have three parameters: the finger ID, and the X and Y coordinates of the tap. This is untested so far, but I'll make sure it works before release tomorrow.
