### ISSUE TITLE
libharu/libhpdf cannot be found on MacOS

### ISSUE THREAD

**Issue by Malmz** [MCJack123/craftos2#287]
**Describe the bug**
Version 2.7.1 crashes on launch on MacOS 12.6.
Tries to load libharu/libhpdf dylib but fails

**To Reproduce**
1. Download 2.7.1 from website
2. Launch
3. Crash

**Expected behavior**
For the applications to launch. 

**Environment (please complete the following information):**
 - OS: MacOS
 - OS Version: 12.6
 - CraftOS-PC Version: 2.7.1
 - Compiled from source? No

**Additional context**
Relevant part of crash report

```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/libharu/lib/libhpdf-2.3.0.dylib'
Referenced from: '/Applications/CraftOS-PC.app/Contents/MacOS/craftos'
Reason: tried: '/usr/local/opt/libharu/lib/libhpdf-2.3.0.dylib' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```

**Comment by MCJack123** [comment]
Turns out the build process was missing some commands required to make libraries work properly on Apple Silicon systems. I've re-released v2.7.1 with the new build process, which should fix your issue.
