### ISSUE TITLE
Debugger crash when breaking on error from library

### ISSUE THREAD

**Issue by pvdosev** [MCJack123/craftos2#294]
**Describe the bug**
The debugger crashes with `debug/debugger.lua:43: attempt to perform arithmetic on a nil value` after `break error` if the error is thrown from a `require`d file.

**To Reproduce**
Make these files:

foo.lua:
```lua
local function foo()
  error("oh no!")
  return 1
end

return foo
```
test.lua:
```lua
local foo = require("foo")

periphemu.create("left", "debugger")
debug.debug()
foo()
```
Run test.lua, then at the debugger enter `catch error`
The debugger will immediately error out.

**Expected behavior**
The debugger works correctly

**Environment (please complete the following information):**
 - OS: Arch Linux
 - OS Version: N/A
 - CraftOS-PC Version: `CraftOS-PC v2.7.2 Built with: cli webp mixer print_pdf`
 - Compiled from source? Yes, the AUR version

**Comment by MCJack123** [comment]
This should be fixed as of MCJack123/craftos2-rom@6c7a94cc2e2dcc12aa8ac379ca2c06bb1224661a.
