### ISSUE TITLE
Ctrl+T does not work

### ISSUE THREAD

**Issue by Creepercdn** [MCJack123/craftos2#305]
**Describe the bug**
Ctrl+T does not work

**To Reproduce**
1. Press Ctrl+T
2. Nothing happens

**Expected behavior**
Terminate it

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 22H2
 - CraftOS-PC Version: v2.7.2
 - Compiled from source?: No

**Additional context**

**Comment by MCJack123** [comment]
Hold Ctrl+T.
