### ISSUE TITLE
Console mode doesn't work

### ISSUE THREAD

**Issue by Craftman2868** [MCJack123/craftos2#308]
On Windows, when I try to start CraftOS-PC in console mode it crash and I got the error "CraftOS Terminal: Computer 0An unexpected error occurred in a Lua function: bios.lua:loadAPI:652: bios.lua:652: Failed to load API gps due to rom/apis/gps.lua:38: malformed number near '0.999'" and segmentation fault, **I don't got this error when I start CraftOS-PC in normal mode**. I have got the same error in Ubuntu but without segmentation fault.

In Windows:
![Capture CraftOS-PC crash](https://user-images.githubusercontent.com/57369130/211158390-7c6f686b-1735-4283-bb29-8bd6ad0951e5.PNG)

OS: Windows 7 pro (I got the same error in Ubuntu 22)
OS Version: 2009
CraftOS-PC Version: CraftOS-PC v2.7.2
Compiled from source? No

**Comment by MCJack123** [comment]
This sounds like a very specific issue with your computer and filesystem that I'm not going to be able to test or control for. The errors it's giving are basically impossible to have happen unless something's really wrong with the system. You're on your own unless you can find a reliable way to reproduce the problem on *any system*.

**Comment by Craftman2868** [comment]
I tested on another PC (Windows 10), it worked perfectly before doing the update but after doing it, I got the same error.
It's been 3 different computers (with different os) that I have the same error.
