### ISSUE TITLE
CraftOS-PC gets detected by G Hub as Kerbal Space Program, causing incorrect settings

### ISSUE THREAD

**Issue by EmmaKnijn** [MCJack123/craftos2#316]
**Describe the bug**
When you open CraftOS-PC and use G Hub, if Kerbal Space Program is installed, it'll detect CraftOS-PC as Kerbal Space Program

**To Reproduce**
1. Make sure G Hub is opened
2. Open CraftOS-PC
3. Click between a normal window and CraftOS-PC

**Expected behavior**
I'd expect G Hub to not switch at all, or at least switch to CraftOS-PC

**Screenshots**

https://user-images.githubusercontent.com/64010592/220729088-42831f96-b9f2-481f-b4f0-f2708f45b23e.mp4

**Environment (please complete the following information):**
 - OS: Windows 11
 - OS Version: 22H2 (Build 22621.1265)
 - CraftOS-PC Version: v2.7.3
 - Compiled from source? No

**Comment by MCJack123** [comment]
There is nothing I can do about this. Contact Logitech if it really affects you that much.
