### ISSUE TITLE
Window icons missing on Wayland

### ISSUE THREAD

**Issue by Commandcracker** [MCJack123/craftos2#320]
**Describe the bug**

Window icons are missing on Wayland.

**Screenshots**

X11
![image](https://github.com/MCJack123/craftos2/assets/49335821/664b8fc3-d6dc-4fa6-a157-351fbd4aa013)

Wayland
![image](https://github.com/MCJack123/craftos2/assets/49335821/bad07d3c-02e8-4edb-af49-115c2a381adc)

**Environment (please complete the following information):**

 - OS: fedora
 - OS Version: 38
 - CraftOS-PC Version: 2.7.4
 - Compiled from source? [Yes](https://github.com/Commandcracker/craftos2-rpm)

**Comment by MCJack123** [comment]
This is an issue with SDL that I can't fix. [Go file an issue there if it's a concern.](https://github.com/libsdl-org/SDL/issues)
