### ISSUE TITLE
Crash when maximizing debugger on Windows

### ISSUE THREAD

**Issue by znepb** [MCJack123/craftos2#321]
**Describe the bug**
CraftOS-PC crashes when maximizing the debugger window.

**To Reproduce**
1. Attach a debugger
2. Maximize the debugger window

**Expected behavior**
CraftOS-PC does not crash.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 22H2 (build 19045.2965)
 - CraftOS-PC Version: Latest I think?
 - Compiled from source? No
 
**Additional context**
n/a

**Comment by MCJack123** [comment]
I can't seem to reproduce this issue anymore. If you're still seeing issues once v2.8 is out, re-open this issue.
