### ISSUE TITLE
Attempting to create a secondary computer causes the 

### ISSUE THREAD

**Issue by pontaoski** [MCJack123/craftos2#322]
Running `attach 1 computer` causes craftos to hang.

Backtraces:
<details>
<pre><code>
Thread 18 (Thread 0x7fff9ffff6c0 (LWP 64442) "craftos:gdrv0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555575dd308) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x5555575dd308, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555575dd308, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555575dd2b8, cond=0x5555575dd2e0) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5555575dd2e0, mutex=0x5555575dd2b8) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 17 (Thread 0x7fffbcbfe6c0 (LWP 64441) "crafto:traceq0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5555574fd770) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x5555574fd770, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5555574fd770, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555574fd720, cond=0x5555574fd748) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5555574fd748, mutex=0x5555574fd720) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 14 (Thread 0x7fffbd3ff6c0 (LWP 64438) "craftos:sh5"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 13 (Thread 0x7fffc8ffd6c0 (LWP 64437) "craftos:sh4"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 12 (Thread 0x7fffc97fe6c0 (LWP 64436) "craftos:sh3"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
--Type <RET> for more, q to quit, c to continue without paging--c
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 11 (Thread 0x7fffc9fff6c0 (LWP 64435) "craftos:sh2"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 10 (Thread 0x7fffd8e106c0 (LWP 64434) "craftos:sh1"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 9 (Thread 0x7fffd96116c0 (LWP 64433) "craftos:sh0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55555758c968) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55555758c968, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55555758c918, cond=0x55555758c940) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55555758c940, mutex=0x55555758c918) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 8 (Thread 0x7fffd9e126c0 (LWP 64432) "craftos:disk$0"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x555557595428) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x555557595428, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x555557595428, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555575953d8, cond=0x555557595400) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x555557595400, mutex=0x5555575953d8) at pthread_cond_wait.c:618
#5  0x00007fffca10d5bd in cnd_wait () from /usr/lib64/dri/iris_dri.so
#6  0x00007fffca0bda4b in util_queue_thread_func () from /usr/lib64/dri/iris_dri.so
#7  0x00007fffca10d4eb in impl_thrd_routine () from /usr/lib64/dri/iris_dri.so
#8  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#9  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7fffda7fc6c0 (LWP 64431) "SDLTimer"):
#0  futex_wait (private=0, expected=2, futex_word=0x5555556f7f10 <taskQueue+80>) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x5555556f7f10 <taskQueue+80>, private=0) at lowlevellock.c:49
#2  0x00007ffff72b1412 in lll_mutex_lock_optimized (mutex=0x5555556f7f10 <taskQueue+80>) at pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x5555556f7f10 <taskQueue+80>) at pthread_mutex_lock.c:93
#4  0x00005555555aaca1 in __gthread_mutex_lock (__mutex=<optimized out>) at /usr/include/c++/12/x86_64-redhat-linux/bits/gthr-default.h:749
#5  std::mutex::lock (this=<optimized out>) at /usr/include/c++/12/bits/std_mutex.h:100
#6  std::unique_lock<std::mutex>::lock (this=0x7fffda7fbc10) at /usr/include/c++/12/bits/unique_lock.h:139
#7  std::unique_lock<std::mutex>::unique_lock (__m=..., this=<optimized out>, this=<optimized out>, __m=...) at /usr/include/c++/12/bits/unique_lock.h:69
#8  queueTask(std::function<void* (void*)> const&, void*, bool) (func=..., arg=0x7fffda7fbcc0, async=<optimized out>) at src/runtime.cpp:76
#9  0x00005555555b0053 in eventTimeoutEvent (interval=<optimized out>, param=0x5555574dd870) at src/runtime.cpp:208
#10 0x00007ffff7863595 in SDL_TimerThread () from /lib64/libSDL2-2.0.so.0
#11 0x00007ffff790c687 in RunThread.lto_priv.0 () from /lib64/libSDL2-2.0.so.0
#12 0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#13 0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7fffdaffd6c0 (LWP 64430) "craftos"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7fffc4134bd0) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7fffc4134bd0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:87
#2  0x00007ffff72aad7f in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7fffc4134bd0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#3  0x00007ffff72ad510 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7fffc4134b80, cond=0x7fffc4134ba8) at pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x7fffc4134ba8, mutex=0x7fffc4134b80) at pthread_cond_wait.c:618
#5  0x00007ffff74d5110 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib64/libstdc++.so.6
#6  0x00005555555aad4b in queueTask(std::function<void* (void*)> const&, void*, bool) (func=..., arg=<optimized out>, async=<optimized out>) at src/runtime.cpp:89
#7  0x00005555555fb0d9 in computer::computer (side=<optimized out>, L=0x7fffc4125770, this=0x7fffc40df3c0) at src/peripheral/computer_p.cpp:63
#8  computer::init (L=0x7fffc4125770, side=<optimized out>) at src/apis/../peripheral/computer.hpp:27
#9  0x0000555555600e47 in std::function<peripheral* (lua_State*, char const*)>::operator()(lua_State*, char const*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/std_function.h:591
#10 attachPeripheral (computer=computer@entry=0x5555574dd870, side="computer_1", type="computer", errorReturn=errorReturn@entry=0x7fffdaffabc0, format=format@entry=0x55555564a4c3 "L") at src/apis/periphemu.cpp:102
#11 0x0000555555601506 in periphemu_create (L=0x7fffc4125770) at src/apis/periphemu.cpp:149
#12 0x00007ffff7f6a378 in luaD_precall (L=L@entry=0x7fffc4125770, func=0x7fffc4137a00, nresults=nresults@entry=2) at ldo.c:447
#13 0x00007ffff7f76ad3 in luaV_execute (L=L@entry=0x7fffc4125770) at lvm.c:840
#14 0x00007ffff7f6a968 in f_costart (L=L@entry=0x7fffc4125770, ud=ud@entry=0x7fffc4122b40) at ldo.c:539
#15 0x00007ffff7f69618 in luaD_rawrunprotected (L=L@entry=0x7fffc4125770, f=0x7ffff7f6a940 <f_costart>, ud=0x7fffc4122b40) at ldo.c:138
#16 0x00007ffff7f6aa5d in lua_resume (L=L@entry=0x7fffc4125770, nargs=nargs@entry=2) at ldo.c:587
#17 0x00007ffff7f7b138 in auxresume (L=L@entry=0x7fffc41003b0, co=co@entry=0x7fffc4125770, narg=2) at lbaselib.c:592
#18 0x00007ffff7f7b241 in luaB_coresume (L=0x7fffc41003b0) at lbaselib.c:614
#19 0x00007ffff7f6a378 in luaD_precall (L=L@entry=0x7fffc41003b0, func=0x7fffc41161b0, nresults=nresults@entry=-1) at ldo.c:447
#20 0x00007ffff7f76ad3 in luaV_execute (L=L@entry=0x7fffc41003b0) at lvm.c:840
#21 0x00007ffff7f69ffd in f_continue (L=0x7fffc41003b0, ud=0x0) at ldo.c:163
#22 0x00007ffff7f69618 in luaD_rawrunprotected (L=L@entry=0x7fffc41003b0, f=0x7ffff7f6a020 <f_coresume>, ud=0x7fffc4116080) at ldo.c:138
#23 0x00007ffff7f6aa5d in lua_resume (L=L@entry=0x7fffc41003b0, nargs=nargs@entry=3) at ldo.c:587
#24 0x00007ffff7f7b138 in auxresume (L=L@entry=0x7fffc4091770, co=co@entry=0x7fffc41003b0, narg=3) at lbaselib.c:592
#25 0x00007ffff7f7b241 in luaB_coresume (L=0x7fffc4091770) at lbaselib.c:614
#26 0x00007ffff7f6a378 in luaD_precall (L=L@entry=0x7fffc4091770, func=0x7fffc4104cd0, nresults=nresults@entry=2) at ldo.c:447
#27 0x00007ffff7f76ad3 in luaV_execute (L=L@entry=0x7fffc4091770) at lvm.c:840
#28 0x00007ffff7f69ffd in f_continue (L=0x7fffc4091770, ud=0x0) at ldo.c:163
#29 0x00007ffff7f69618 in luaD_rawrunprotected (L=L@entry=0x7fffc4091770, f=0x7ffff7f6a020 <f_coresume>, ud=0x7fffc4104c40) at ldo.c:138
#30 0x00007ffff7f6aa5d in lua_resume (L=L@entry=0x7fffc4091770, nargs=nargs@entry=3) at ldo.c:587
#31 0x00007ffff7f7b138 in auxresume (L=L@entry=0x7fffc406fc50, co=co@entry=0x7fffc4091770, narg=3) at lbaselib.c:592
#32 0x00007ffff7f7b241 in luaB_coresume (L=0x7fffc406fc50) at lbaselib.c:614
#33 0x00007ffff7f6a378 in luaD_precall (L=L@entry=0x7fffc406fc50, func=0x7fffc407fec0, nresults=nresults@entry=2) at ldo.c:447
#34 0x00007ffff7f76ad3 in luaV_execute (L=L@entry=0x7fffc406fc50) at lvm.c:840
#35 0x00007ffff7f69ffd in f_continue (L=0x7fffc406fc50, ud=0x0) at ldo.c:163
#36 0x00007ffff7f69618 in luaD_rawrunprotected (L=L@entry=0x7fffc406fc50, f=0x7ffff7f6a020 <f_coresume>, ud=0x7fffc407fec0) at ldo.c:138
#37 0x00007ffff7f6aa5d in lua_resume (L=0x7fffc406fc50, nargs=<optimized out>) at ldo.c:587
#38 0x00005555556382fe in runComputer(Computer*, std::filesystem::__cxx11::path const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .constprop.0] (self=0x5555574dd870, bios_name=filesystem::path "bios.lua", bios_data=...) at src/Computer.cpp:663
#39 0x0000555555597ab1 in computerThread (data=0x5555574dd870) at src/Computer.cpp:799
#40 0x00007ffff74dbc43 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#41 0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#42 0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7fffdbfff6c0 (LWP 64424) "SDLAudioP2"):
#0  0x00007ffff7322316 in __ppoll (fds=0x5555574c29c0, nfds=2, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#1  0x00007ffff671b361 in pa_mainloop_poll () from /lib64/libpulse.so.0
#2  0x00007ffff6725a4a in pa_mainloop_iterate () from /lib64/libpulse.so.0
#3  0x00007ffff78c5539 in PULSEAUDIO_PlayDevice () from /lib64/libSDL2-2.0.so.0
#4  0x00007ffff78026ca in SDL_RunAudio () from /lib64/libSDL2-2.0.so.0
#5  0x00007ffff790c687 in RunThread.lto_priv.0 () from /lib64/libSDL2-2.0.so.0
#6  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#7  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7fffe4cda6c0 (LWP 64423) "Render Thread"):
#0  0x00007ffff72f5005 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffe4cd9e30, rem=0x7fffe4cd9e30) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007ffff72f97b7 in __GI___nanosleep (req=<optimized out>, rem=<optimized out>) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00005555555c8431 in std::this_thread::sleep_for<long, std::ratio<1l, 1000000l> > (__rtime=...) at /usr/include/c++/12/bits/this_thread_sleep.h:80
#3  termRenderLoop () at src/termsupport.cpp:644
#4  0x00007ffff74dbc43 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#5  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#6  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7fffe4d1b6c0 (LWP 64422) "PulseHotplug"):
#0  0x00007ffff7322316 in __ppoll (fds=0x555557496a90, nfds=2, timeout=<optimized out>, sigmask=0x0) at ../sysdeps/unix/sysv/linux/ppoll.c:42
#1  0x00007ffff671b361 in pa_mainloop_poll () from /lib64/libpulse.so.0
#2  0x00007ffff6725a4a in pa_mainloop_iterate () from /lib64/libpulse.so.0
#3  0x00007ffff6725af0 in pa_mainloop_run () from /lib64/libpulse.so.0
#4  0x00007ffff78c6373 in HotplugThread () from /lib64/libSDL2-2.0.so.0
#5  0x00007ffff790c687 in RunThread.lto_priv.0 () from /lib64/libSDL2-2.0.so.0
#6  0x00007ffff72ae12d in start_thread (arg=<optimized out>) at pthread_create.c:442
#7  0x00007ffff732fbc0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7ffff763d380 (LWP 64417) "craftos"):
#0  futex_wait (private=0, expected=2, futex_word=0x5555556f7f10 <taskQueue+80>) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x5555556f7f10 <taskQueue+80>, private=0) at lowlevellock.c:49
#2  0x00007ffff72b1412 in lll_mutex_lock_optimized (mutex=0x5555556f7f10 <taskQueue+80>) at pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x5555556f7f10 <taskQueue+80>) at pthread_mutex_lock.c:93
#4  0x00005555555aaca1 in __gthread_mutex_lock (__mutex=<optimized out>) at /usr/include/c++/12/x86_64-redhat-linux/bits/gthr-default.h:749
#5  std::mutex::lock (this=<optimized out>) at /usr/include/c++/12/bits/std_mutex.h:100
#6  std::unique_lock<std::mutex>::lock (this=0x7fffffffd740) at /usr/include/c++/12/bits/unique_lock.h:139
#7  std::unique_lock<std::mutex>::unique_lock (__m=..., this=<optimized out>, this=<optimized out>, __m=...) at /usr/include/c++/12/bits/unique_lock.h:69
#8  queueTask(std::function<void* (void*)> const&, void*, bool) (func=..., arg=0x5555582ae740, async=<optimized out>) at src/runtime.cpp:76
#9  0x000055555561a5cb in SDLTerminal::onActivate (this=0x555558287b80) at src/terminal/SDLTerminal.cpp:594
#10 SDLTerminal::SDLTerminal (this=<optimized out>, title=..., this=<optimized out>, title=...) at src/terminal/SDLTerminal.cpp:177
#11 0x00005555555c7ded in TerminalFactoryImpl<SDLTerminal>::createTerminal (this=0x5555556f77a8 <SDLTerminalFactory>, title="CraftOS Terminal: Computer 1") at src/termsupport.cpp:250
#12 0x0000555555593e63 in Computer::Computer (this=<optimized out>, i=<optimized out>, debug=<optimized out>, this=<optimized out>, i=<optimized out>, debug=<optimized out>) at src/Computer.cpp:87
#13 0x0000555555595905 in Computer::Computer (i=1, this=0x5555582723c0) at ./api/Computer.hpp:147
#14 startComputer (id=1) at src/Computer.cpp:868
#15 0x00005555555ada08 in std::function<void* (void*)>::operator()(void*) const (__args#0=<optimized out>, this=0x7fffc4134b50) at /usr/include/c++/12/bits/std_function.h:591
#16 pumpTaskQueue () at src/runtime.cpp:132
#17 0x00005555555ccf1d in SDLTerminal::pollEvents () at src/terminal/SDLTerminal.cpp:688
#18 TerminalFactoryImpl<SDLTerminal>::pollEvents (this=<optimized out>) at src/termsupport.cpp:254
#19 0x00005555555ae837 in mainLoop () at src/runtime.cpp:171
#20 0x00005555555882a4 in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:822
</code></pre>
</details>

**Environment (please complete the following information):**
 - OS: Fedora
 - OS Version: 37
 - CraftOS-PC Version: 2.7.4
 - Compiled from source? No

**Comment by MCJack123** [comment]
Reinstall the package. This was an issue in an early version of CCPC that ended up in the Fedora package, which was rebuilt two days ago to fix this. If this fails, make an issue at https://github.com/LeMoonStar/craftos2-rpm.
