### ISSUE TITLE
crash on loading API

### ISSUE THREAD

**Issue by gameplays12303** [MCJack123/craftos2#323]
I'm building my own bios and while trying to load some of the Craft-OS APIS the computer simply crashes and i can't find out what's going wrong here  this is the dump file it created , with a argument of handle C fs 
just tried it again and the computer itself locked up am i missing some APIS or simply bad loading 

please note this a dump file just using the log extension to bypass the system 
~~CraftOS-PC.exe.53872.LOG~~ (redacted for user safety)

**Comment by MCJack123** [comment]
Please update to CraftOS-PC v2.7.4. Also, please use the bug report template next time to fill in important information.
