### ISSUE TITLE
Pop-ups freeze term

### ISSUE THREAD

**Issue by tizu69** [MCJack123/craftos2#324]
**Describe the bug**
![image](https://github.com/MCJack123/craftos2/assets/60812901/6cdd81c8-e2de-4b22-b074-2bb3c72e7125)
These dialog message boxes freeze the term, causing weird behavior if used with a tiling WM

**To Reproduce**
1. Get some old COS version
2. start it while having a tiling wm on
3. the dialog won't tile and likely stay in the bg, making you think COS is frozen

**Expected behavior**
Possible solutions:
- The Computer should just run
- Show the dialog in the computer
  ![image](https://github.com/MCJack123/craftos2/assets/60812901/40fcfdcb-beeb-41c1-9535-db757c108b96)
- Tell the user there's something going on
  ![image](https://github.com/MCJack123/craftos2/assets/60812901/5475c86c-6e6e-4c38-882b-097f71106476)

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64 (thanks, neofetch)
 
 - CraftOS-PC Version: 2.7.4, this is the cause basically (CraftOS 1.8)
 - Compiled from source? I'm not running gentoo. no.

**Additional context**

**Comment by MCJack123** [comment]
Not a bug, or at least one I can fix. Dialog boxes block rendering until they're interacted with, and there's nothing I can do about that.

**Comment by tizu69** [comment]
How can it not be possible to write something to the term before checking for updates? before opening the dialog, render a message, then freeze as usual
