### ISSUE TITLE
Feature idea: Opening Android apps

### ISSUE THREAD

**Issue by OwOsucksAwesomeMinecraftbossAlissha6TRM** [MCJack123/craftos2#325]
**Is your feature request related to a problem? Please describe.**
I love computercraft, and it would be cool if I could have a computercraft like GUI for my phone 

**Describe the solution you'd like**
Make a way to open Android apps with CraftOS app, either a peripheral you can attach or a function under "os" like "os.openApp("Reddit")"

**Describe alternatives you've considered**
maybe you could make a cc launcher for Android, so when you open your phone, it goes to a custom program you made, that can also open Android apps

**Additional context**

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
For iPhones, you could make it be able to run shortcuts, would be really useful for cc


Maybe you could do the same with Android somehow, like allowing to turn volume up and down, seeing notifications, getting battery percentage, etc

**Comment by OwOsucksAwesomeMinecraftbossAlissha6TRM** [comment]
maybe you could also allow for CraftOS to open in a picture on picture window, not sure if it's possible for iPhone, but Android it might be possible, would be cool

**Comment by MCJack123** [comment]
1. Interacting with the outside OS, including opening apps, is out of scope for CraftOS-PC, especially on mobile platforms. I don't intend on adding any features that break outside of the computer's environment, unless required to make the app usable.
2. PiP requires a video stream to operate, so it's not possible to integrate the app into PiP. Even if it were possible, the screen would be incredibly small to the point of being useless.
