### ISSUE TITLE
Error when trying to edit a file with a nonexistent directory

### ISSUE THREAD

**Issue by AlphaTechNinja** [MCJack123/craftos2#330]
When I try to make a file in a dictionary that doesn't exist yet it gives errors saying "No such path" even though ComputerCraft is supposed to auto create directorys 
when the path doesn't exist

To see this bug type in
edit somepath/file.lua
you will get error 
/rom/programs/edit.lua:114:
/somepath/file.lua: No such path

I'm running this on the mobile IOS app

This happened after a recent update

**Comment by AlphaTechNinja** [comment]
Issue still persists
It seems it's in the actual editing program in rom it says 
On line 144 in if statement
```Lua
if not bReadOnly and fs.getFreeSpace(sPath) < 1024 then
set_status("Disk is low on space")
else
local message
...
```

Results in the error message saying no such. I suspect the error is being caused in the fs library getFreeSpace function when 
the path doesn't exists

**Comment by AlphaTechNinja** [comment]
Fixed in Lua side by changing
```Lua
if not bReadOnly and fs.getFreeSpace(sPath) < 1024 then
...
```
To
```Lua
if not bReadOnly and fs.exists(sPath) and fs.getFreeSpace(sPath) < 1024 then
...
```

**Comment by MCJack123** [comment]
The fix hasn't been merged yet. Please wait for v2.8 to merge.

**Comment by AlphaTechNinja** [comment]
Thank you for merging this update to the IOS app it seems to have fixed the issue
