### ISSUE TITLE
On Android, cannot open peripheral/keyboard menu

### ISSUE THREAD

**Issue by Lilygabe** [MCJack123/craftos2#338]
**Describe the bug**
I am not sure if this is a bug or lack of documentation, but there doesn't seem to be a way to open the keyboard / peripherals menu on android.

**To Reproduce**
1. Open app
2. Close keyboard
3. Notice how there is no indication for how to open the menu

**Expected behavior**
An indication of how to open the menu

**Screenshots**
![Screenshot_20231231_005033_CraftOS-PC](https://github.com/MCJack123/craftos2/assets/72508863/d5684240-8245-409d-833c-f8557edc0fe2)

**Environment (please complete the following information):**
 - OS: Android
 - OS Version: **13**
 - CraftOS-PC Version: 2.7.5
 - Compiled from source? [No]

**Additional context**
-

**Comment by MCJack123** [comment]
You have to tap with two fingers to open the navigation menu, and then you can press the keyboard button. I know this isn't obvious at all, which is why I'm implementing a welcome screen to tell you this in v2.8. Sorry for the confusion!
