### ISSUE TITLE
CraftOS-PC Accelerated hangs when opening new computer

### ISSUE THREAD

**Issue by MichielP1807** [MCJack123/craftos2#356]
**Describe the bug**
When you (or a Lua program) opens a new computer, CraftOS-PC Accelerated, inputs in the new computer are really slow, and the original computer seems to freeze and become unusable. 

**To Reproduce**
1. Open CraftOS-PC Accelerated v2.8+
2. Type `attach 1 computer`
3. Try to interact with CraftOS-PC to see how it hangs

**Expected behavior**
Opening a new computer should work normally, like it did in versions before v2.8. In CraftOS-PC Accelerated v2.7.5 everything works as expected. The non-accelerated version also does not have this problem.

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 22H2
 - CraftOS-PC Version: [CraftOS-PC Accelerated v2.8.2](https://github.com/MCJack123/craftos2/releases/tag/v2.8.2-luajit), [CraftOS-PC Accelerated v2.8](https://github.com/MCJack123/craftos2/releases/tag/v2.8-luajit)
 - Compiled from source? No

**Comment by MCJack123** [comment]
This is fixed in the latest commit.
