### ISSUE TITLE
[CRITICAL] False positive detected upon CraftOS-PC installation

### ISSUE THREAD

**Issue by QM8782** [MCJack123/craftos2#357]
**Describe the bug**
This started while updating, and this is critical as a line of code in the emulator seems to cause a false-positive.

**To Reproduce**
1. Go to the download
2. Click on run
3. A message pops up that says cannot run due to a virus or potentially unwanted program

**Expected behavior**
A uninterrupted update/installation

**Environment**
 - OS: Windows 10/11
 - OS Version: any build
 - CraftOS-PC Version: 2.8.2
 - Compiled from source? - No, was already compiled on installation

**Comment by MCJack123** [comment]
False positives happen sometimes, often due to Inno Setup, and there's nothing I can do about it. If you're having issues, check VirusTotal for low to zero detections (currently there is 1, which is a false positive), then disable Defender temporarily to install.
