### ISSUE TITLE
Issue with ModPlug_Load in Speaker function

### ISSUE THREAD

**Issue by QM8782** [MCJack123/craftos2#363]
**Describe the bug**
I have an issue. I am trying play a converted DFPWM file, aaaand it's erroring when I run it...

```
Could not load music file: ModPlug_Load failed
```

All my devices are working, why is not CraftOS-PC doing so as well? I even updated and it's still broken.

```Lua
-- s is the variable I assigned it to
s.playLocalMusic("/sys/snd/startup.dfpwm")
```

Any clue how to fix it? Thanks, -QM-

**To Reproduce**
1. Go to Lua
2. Wrap speaker
3. Play direct file

**Expected behavior**
To play the sound without failing...

**Screenshots**
If applicable, add screenshots or recordings to help explain your problem. You can capture these using F2, F3, or F12. If CraftOS-PC has crashed, paste the stack trace here (wrapped in \`\`\` characters please!).

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - OS Version: [e.g. 2004] (this can be found in Settings -> System -> About)
 - CraftOS-PC Version: [e.g. v2.2]
 - Compiled from source? [Yes] [No] (if in doubt, choose No)

**Additional context**

**Comment by MCJack123** [comment]
`playLocalMusic` isn't the correct function to use - it's a custom CCPC function made before the standard `playAudio` method, and doesn't support DFPWM. Use [this guide](https://tweaked.cc/guide/speaker_audio.html) to play audio in CC.
