### ISSUE TITLE
Package 'craftos-pc' has no installation candidate (Linux Mint 22)

### ISSUE THREAD

**Issue by KarmyDev** [MCJack123/craftos2#364]
**Describe the bug**
Cannot install craftos-pc via terminal/apt. Missing package?

**To Reproduce**
1. Open Terminal on Linux Mint 22
2. Run the following commands:
```yml
sudo add-apt-repository ppa:jackmacwindows/ppa
sudo apt update
sudo apt install craftos-pc
```
3. See error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package craftos-pc is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'craftos-pc' has no installation candidate
```

**Environment (please complete the following information):**
 - OS: Linux Mint 22
 - OS Version: Linux Mint 22 Wilma, base: Ubuntu 24.04 noble
 - CraftOS-PC Version: latest available in apt
 - Compiled from source? No

**Comment by tomodachi94** [comment]
A `craftos-pc` package for Noble doesn't appear to exist (though an accelerated variant does): https://launchpad.net/~jackmacwindows/+archive/ubuntu/ppa/+packages

**Comment by MCJack123** [comment]
CraftOS-PC is now available for Noble as of v2.8.3.

**Comment by CatChris2014** [comment]
actually it isnt in the page u shared

**Comment by CatChris2014** [comment]
oh nvm that was the other guy

**Comment by CatChris2014** [comment]
but i still cant find it
