### ISSUE TITLE
constant crashing after install

### ISSUE THREAD

**Issue by TheG0dC0der** [MCJack123/craftos2#369]
**Describe the bug**
can't use craft os after install

**To Reproduce**
1. install craftos-pc-setup
2. finish setup
3. run craftos
4. crash

**Expected behavior**
for it to start and not crash

**Screenshots**
![image](https://github.com/user-attachments/assets/2e882c04-af78-492f-88d1-40d2ebdd091f)
[CraftOS-PC.exe.3636.dmp](https://github.com/user-attachments/files/16657631/CraftOS-PC.exe.3636.dmp)
Last C function: (none!)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 22H2
 - CraftOS-PC Version: 2.8.3
 - Compiled from source? no

**Additional context**

**Comment by pat600130** [comment]
I'm having the same issue 
and my message error is the same
OS: Windows 10
CraftOS-PC Version: 2.8.3
[CraftOS-PC.exe.19208.dmp](https://github.com/user-attachments/files/16919144/CraftOS-PC.exe.19208.dmp)

**Comment by jig487** [comment]
same issue, same error message.
Windows 10
CraftOS-PC v2.8.3
[CraftOS-PC.exe.10976.dmp](https://github.com/user-attachments/files/17211175/CraftOS-PC.exe.10976.dmp)

**Comment by MCJack123** [comment]
Try installing the latest [Visual C++ 2022 redistributable](https://aka.ms/vs/17/release/vc_redist.x64.exe) and see if this issue is resolved.

**Comment by MCJack123** [comment]
From others it appears this fixes the issue. The next version will include an updated redistributable.
