### ISSUE TITLE
Missing critical terminal function that broke every program I write that relies on it.

### ISSUE THREAD

**Issue by QM8782** [MCJack123/craftos2#384]
**Describe the bug**
I have came across `term.getLine` removed from `term.current`, and only returns `term.getLine` when `window.create` has the `term.current()` object via given in the parent argument (arg no. 1)  and is very much a problem because I want to utilise the terminal API, not CraftOS's built-in Window API. This is critical because my programs rely on this for previous frame redraw. This has the same issue on `term.native` which is frustrating.

**To Reproduce**
Open the emulator on the current version (2.8.3) to do the same results I got on my end.
- Open Lua (type `lua` and press enter)
- Type `term.current()` and press enter. You'll see that `.getLine(y)` is not there. It's a crucial function, and this is a problem when you're making something that redraws the screen after program execution.
- Now type `window.create(term.current(), 1, 1, 1, 1, false)` and press enter. You can see `.getLine(y)` is there, yet on the main terminal it isn't there.

**Expected behavior**
`term.getLine` available and no errors for my programs that use the function. Since there are errors and this function doesn't return it, it will be a problem when I run certain code that I made myself that I store. Please bring the function back so things are fixed.

**Environment (please complete the following information):**
 - OS: Windows 11 Professional
 - OS Version: 23H2
 - CraftOS-PC Version: 2.8.3
 - Compiled from source?: No

**Comment by MCJack123** [comment]
Not a bug. Don't rely on the current terminal object being a window.
