### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#49]
It has been suggested that I rename this project, but I'm not sure what it should be named. If you would like to suggest a new name, post it here.

**Comment by Emexus** [comment]
Cactus / CactOS

**Comment by daelvn** [comment]
> Cactus / CactOS

Not an OS. I would be okay with Cactus. I guess. I don't know.

**Comment by Ocawesome101** [comment]
Ideas:

`CC: Terminal`

`CCTerminal`

`CCTerminal`

`CCTerm`

`CC: Desktop`
