### ISSUE TITLE
Headless mode doesn't quite work (Ubuntu 19.04)

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#51]
I am using Ubuntu 19.04, as the title says. Non-headless (windowed) mode works perfectly (except for GitGet, see my other issue which I'll open after this one), but headless (terminal) mode doesn't quite. It starts, I see a prompt, but I type 'ls', press Enter, and the entire thing stops responding. I can close the terminal window, and type, and press Ctrl-C, but `craftos --headless` doesn't respond.

This probably is something worth fixing.

**Comment by MCJack123** [comment]
Headless mode is for running a script without any input; you're looking for the `--cli` flag.

**Comment by Ocawesome101** [comment]
> Headless mode is for running a script without any input; you're looking for the `--cli` flag.

Ohhh, thank you! :)
