### ISSUE TITLE
Printing to the screen is slow

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#55]
So my custom OS ([this](https://github.com/ocawesome101/oc-linux-cc)) now runs, but during boot it is quite slow and timestamps don't work quite right (they stay at 0.00 the whole time).

Under CCEmuX, the "OS" boots quite quickly. However, under CraftOS-PC 2, it boots rather slowly, though once in the shell it runs fine. I suspect this is due to the amount of text logged while booting.

Please fix this, as this otherwise is a really, really nice emulator (fast, pretty stable, and lightweight).

**Comment by MCJack123** [comment]
1. I'm not seeing any slowdowns on my machine (Windows 10), even when using oc-linux. What OS are you running CraftOS-PC on?
2. The `os.time()` function returns the time in real hours. This is meant to parallel the Minecraft implementation where `os.time()` returns the in-game hour. `os.epoch("utc")` returns milliseconds no matter what, so you might want to consider using that instead (though it's a CC 1.8 feature).

**Comment by Ocawesome101** [comment]
Ahh, okay. I changed a line of code (`os.sleep(0.0001)` to
`os.sleep(0.01)`) and it has sped up greatly (I’m running Ubuntu 19.04).

I will start using `os.epoch(“utc”)` instead. I wasn’t planning on
supporting anything earlier than that anyway.
