### ISSUE TITLE
Crash on macOS on rebooting

### ISSUE THREAD

**Issue by Le0Developer** [MCJack123/craftos2#58]
After I typed `reboot` it crashed, and I it showed me this in the Commandline:
```bash
Macbook:~ LeoDeveloper$ /Users/LeoDeveloper/Applications/CraftOS-PC.app/Contents/MacOS/craftos 
Segmentation fault: 11
Macbook:~ LeoDeveloper$ 
```
(paths are changed)

Disclaimer
---
I wasn't able to reproduce this, but I got another crash 30min earlier, when I closed a window, maybe it's related. 

Full crash reports by macOS:
  - Crash on reboot [here](https://pastebin.com/ZJSfwfH8)
  - Crash on window close [here](https://pastebin.com/eRbgmPkU)

**Comment by MCJack123** [comment]
I found a few race conditions that are fixed in the latest commit. (They were two separate issues that were not related.)
