### ISSUE TITLE
[WEB] Download button doesn't work.

### ISSUE THREAD

**Issue by Le0Developer** [MCJack123/craftos2#59]
The download button doesn't work on https://craftos-pc.cc.

It links to https://github.com/MCJack123/craftos2/releases/download/latest/CraftOS-PC.dmg.
The `/latest/` part seems to not work, replacing it with the newest version `v2.1.2` does work.

**Comment by MCJack123** [comment]
It should automatically change `/latest/` to the latest version. It works fine for me, try reloading the page a couple of times.
