### ISSUE TITLE
Strange Visual Bug

### ISSUE THREAD

**Issue by Peekofwar** [MCJack123/craftos2#68]
It seems to be drawing my application up by one pixel for some reason as compared to ComputerCraft: Tweaked's in-game computers.
![emulator error 3](https://user-images.githubusercontent.com/10189526/71538426-b44a7380-28f8-11ea-8772-e162ffb7b0f8.JPG)

For some reason, this dialog box is rendered very strangely compared again to ComputerCraft: Tweaked
![emulator error 1](https://user-images.githubusercontent.com/10189526/71538425-b1e81980-28f8-11ea-94c4-cbeb3226a42c.JPG)

Script used in my testing: https://pastebin.com/HS1djdaV

**Comment by MCJack123** [comment]
This issue is related to `io.write()`: it used to be a wrapper for the `print()` function but now it will call `write()` instead. You can use `write()` as a workaround until the next version is released.
