### ISSUE TITLE
Modern C++

### ISSUE THREAD

**Issue by Lignum** [MCJack123/craftos2#7]
As a heads up, the `platform_*.cpp` files you have contain a lot of code that has been standardised in modern C++ versions, and there's not really much reason to implement them yourself anymore.

Since you're using `chrono`, I'm assuming you're fine using C++11, which has [threads](https://en.cppreference.com/w/cpp/thread/thread) (including `sleep`). Additionally, in [memory](https://en.cppreference.com/w/cpp/header/memory) there's `std::unique_ptr<T>` and `std::shared_ptr<T>` for safe allocations, rather than using `new`/`delete`, the former being a completely free abstraction.

If you're fine with using C++17, there's the [filesystem](https://en.cppreference.com/w/cpp/experimental/fs) library for manipulating directories among other things.

**Comment by MCJack123** [comment]
Thanks for reminding me of those features. I originally learned C++ before C++11 and I often forget these new APIs exist! I'll move over the features supplied in C++11 from `platform.cpp` in the future (I'm going to be moving away from plain C soon), but C++14 and later features may not be included to keep support for any compilers that may not support newer features.

**Comment by Lignum** [comment]
> [..], but C++14 and later features may not be included to keep support for any compilers that may not support newer features.

Fair enough, however it is to be noted that according to [this table](https://en.cppreference.com/w/cpp/compiler_support#cpp14) C++14 is pretty much fully supported on GCC 5 and newer. I think at this point it's safe to go for C++14. I do agree that C++17 might be too new, however.

**Comment by MCJack123** [comment]
I've moved to using `std::thread` for multithreading. There's still a good chunk of code that still uses legacy C routines, so I'm leaving this open for now.

**Comment by MCJack123** [comment]
Superseded by #43, closing.
