### ISSUE TITLE
WASM support?

### ISSUE THREAD

**Issue by Kan18** [MCJack123/craftos2#73]
This is theoretical but since all the platform specific code are in `platform_*` files, maybe CraftOS PC-2 could be compiled with Emscripten and have a `platform_wasm` file.

**Comment by MCJack123** [comment]
Since Emscripten has SDL built-in, most of the user-facing code can be taken care of. I've considered making a WASM port but I would have to rework a lot of the code to run nice under a browser environment. I'm leaving this open as a future possibility.

**Comment by MCJack123** [comment]
A demo of WASM support for CraftOS-PC is available at https://www.craftos-pc.cc/online/. Note that this version is incomplete and has many bugs. Also, it only works on Chrome, or Firefox Developer Edition with `dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled` and `dom.postMessage.sharedArrayBuffer.withCOOP_COEP` enabled in `about:config`. (Normal Firefox does not allow enabling `dom.postMessage.sharedArrayBuffer.bypassCOOP_COEP.insecure.enabled` for security reasons.)
