### ISSUE TITLE
Attempting to Call Graphics Mode when in Vanilla Mode

### ISSUE THREAD

**Issue by Peekofwar** [MCJack123/craftos2#76]
If you launch CraftOS-PC with vanilla mode enabled, it still tries to call Graphics Mode, promptly displaying a nil value error at startup.

Edit: This apparently also prevents the Pastebin program form running scripts.

![big error](https://user-images.githubusercontent.com/10189526/71776121-e479be00-2f59-11ea-8f1d-27181df797f5.JPG)

It seems to have also prevented my startup program from running.

**Comment by MCJack123** [comment]
Fixed in the latest ROM.
