### ISSUE TITLE
fs.list() crash

### ISSUE THREAD

**Issue by Productive2** [MCJack123/craftos2#77]
**Bug description**
Running fs.list() without arguments inside the interactive lua prompt crashes the craftos-pc emulator.
(Running fs.list("/") runs just fine.)

**To Reproduce**
1. Open craftos-pc from the terminal by typing craftos
2. Open the interactive lua prompt inside craftos
3. Type fs.list()
4. Craftos-pc crashes, with the following std-out error in the terminal:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

**Expected behavior**
I don't remember what the CC behaviour is (lua error/listing working directory?). But definitely not crashing craftos.

**Environment (please complete the following information):**
 - OS: Linux mint 19.3, x86-64
 - Version latest from the ubuntu ppa
 - Compiled from source? No
- file system: ext4

**Further notes/testing**
- It happens when starting it using the .desktop shortcut as well, but the error message is not seen
- the crash happens when fs.list() is inside a lua script saved on the disk and executed, too
- running apt list --installed | grep lua outputs:
```
liblua5.1-0/bionic,now 5.1.5-8.1build2 amd64 [installed,automatic]
libluajit-5.1-2/bionic,now 2.1.0~beta3+dfsg-5.1 amd64 [installed,automatic]
libluajit-5.1-common/bionic,bionic,now 2.1.0~beta3+dfsg-5.1 all [installed,automatic]
libtexlua52/bionic-updates,bionic-security,now 2017.20170613.44572-8ubuntu0.1 amd64 [installed,automatic]
libtexluajit2/bionic-updates,bionic-security,now 2017.20170613.44572-8ubuntu0.1 amd64 [installed,automatic]
texlive-luatex/bionic,bionic,now 2017.20180305-1 all [installed,automatic]
```
Before installing craftos-pc, I only had luajit installed, I assume craftOS downloaded lua 5.1 (is it liblua5.1?)

Let me know if you need more info.

Edit: grammar only

**Comment by MCJack123** [comment]
* [`fs.list`](https://wiki.computercraft.cc/Fs.list) requires one argument - the path to list; for example `fs.list("")` will list the root directory.
* I forgot to check for invalid arguments in `fs.list`, so it should now error if you pass an invalid (or no) argument.
