### ISSUE TITLE
some cli mode (ncurses mode) improvement suggestions

### ISSUE THREAD

**Issue by Productive2** [MCJack123/craftos2#78]
# 1. Control key
**Is your feature request related to a problem? Please describe.**
The current ncurses mode blocks the home key to render the control key. You can still press shift+home to use the home key in programs such as edit, but it solution is not optimal.

**Describe the solution you'd like**
Make it configurable for us to choose a ncurses keycode/keyname, or use a combo such as escape+c, which does no harm to other programs (since escape is never used in a cc program, because it quits programs).

# 2. Some weird ncurses key events
Here are some weird ncurses key maps I found, which probably shouldn't happen
shift+numpad0 types "control" or "O2p"
shift+numpad5 types "[1;2E" or "O2u"
(those depend on the terminal program used)
pressing escape a few times (each time a ```key 27 false``` event gets logged), then pressing any other key or waiting a second wait triggers all those escapes to do a key_up 27. Other keys have instant key_ups (yeah I know, ncurses getch doesn't allow key_up)
mouse_click and mouse_up only trigger when dragging

# 3. resizing ncurses craftos-pc-s
resizing terminals bugs programs out, if you resize them small enough (seems like an infinite scroll) (should all of this be a separate bug report?)
on resizing screens, the resize event is forwarded as ```key 410 false``` followed by a ```key_up 410``` instead of ```term_resize```

# 4. argument passing for script mode
allow argument passing for --script="filename"

# 5. PS, offtopic:
I really love the ncurses mode. It opens up potential to run CC programs and edit your real files while not breaking the flow of terminal usage, which for some reason I find really cool. With bash aliases and symlinks (yes they work, I tried) I can soon use "edit" to edit my real files without much hassle :D.

~~edit:
# 6. offtopic:
Ncurses seems to name the key shift+numpad0/shift+insert extremely off. In xterm, shift+insert inserts a random text that was on my screen some time ago when using the editor nano (for example https://duckduckgo.com/html, or even contents of web pages I have opened). xfce-terminal does the same for shift+numpad0 when num lock is on. The given texts are not in my clipboard. edit really last. i know its mostly irrelevant: it is probably partly intentional, since shift+insert seems to be a valid key for "paste" when in gui programs.~~im fucking stupid. There is multiple clipboards in linux, and whenever I select a text, x11's clipboard autocopies it. Shift+insert is a valid keycombo for paste. TIL, sorry to bother you with this part

**Comment by MCJack123** [comment]
I'll be splitting these up into multiple issues so I can track each issue better.

**Comment by MCJack123** [comment]
Pretty much all of the enhancements suggested have been implemented.
* The control & alt keys can now be triggered in four ways depending on the value of the `cliControlKeyMode` (not available from CraftOS):
  * `0` = default behavior (Home = Ctrl, End = Alt, Shift+Home = Home, Shift+End = End)
  * `1` = inverse behavior (Home = Home, End = End, Shift+Home = Ctrl, Shift+End = Alt)
  * `2` = Esc-C hotkey (Escape, C = Control; Escape, A = Alt)
  * `3` = Ctrl-C hotkey (Ctrl+C = Control, Ctrl+\ = Alt)
    * Note that this disables SIGINT and SIGQUIT so you'll have to `kill -SIGTERM` the process if it gets stuck
* The escape key is no longer sent to CraftOS
* Mouse click events now happen immediately
* Resizing windows is now supported and should (hopefully) not crash anymore
* The `--args "<args>"` flag can be used to specify arguments to the startup program

Also, here's a demo `edit` script that you can try:
```lua
-- ~/.edit.lua
local path = ...
if path == nil then os.shutdown(); while true do coroutine.yield() end end
mounter.mount("/realfs", (path:sub(1, 1) == '/' and "/" or "./") .. fs.getDir(path), false)
if not fs.isDir("/realfs") then os.shutdown(); while true do coroutine.yield() end end
shell.run("edit", "/realfs/" .. fs.getName(path))
os.shutdown()
while true do coroutine.yield() end
```
```sh
alias edit="craftos --cli --script ~/.edit.lua --args"
```
