### ISSUE TITLE
Add configurable control key workaround for CLI mode

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#79]
**Is your feature request related to a problem? Please describe.**
Since CLI mode doesn't support the control key as-is, another key must be used as a workaround. Currently the key is set to Home, but it may be beneficial to have that key still work as it should.

**Describe the solution you'd like**
Add a configuration option for setting the Control key combination.

**Describe alternatives you've considered**
N/A

**Additional context**
#78

**Comment by LoganDark** [comment]
Please add an option to remove this override completely
