### ISSUE TITLE
Add filesystem mount "merge" feature?

### ISSUE THREAD

**Issue by MCJack123** [MCJack123/craftos2#94]
**Is your feature request related to a problem? Please describe.**
Adding files to the ROM is somewhat unsupported, so plugins can't add their own programs/APIs to the ROM if wanted.

**Describe the solution you'd like**
Allow multiple filesystems to be "merged together", ex. mounting a directory with `a` and `b`, and a directory with `c` and `d`, to the same path should have `fs.list()` return `{"a", "b", "c", "d"}`.

**Describe alternatives you've considered**
N/A

**Additional context**
The implementation could look something like [unions in the Plan 9 from Bell Labs OS](https://en.wikipedia.org/wiki/Plan_9_from_Bell_Labs#Union_directories_and_namespaces).

**Comment by daelvn** [comment]
This would actually be an extremely useful solution to how COSRun is currently merging imported projects (copying into imports/, copying from imports into computer at run), looking forward to this!
